---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  labels:
    app: pg
spec:
  serviceName: "pg"
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: docker.io/library/postgres:16.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-env
            - secretRef:
                name: pg-secrets
          volumeMounts:
            - name: apphost-pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: apphost-pg-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
