namespace ArgonSharedLogicTest.Expressions.Native;

/// <summary>
/// VP9 WEBM files written by ffmpeg with libvpx-vp9, three frames at 25 fps:
/// <c>ffmpeg -f lavfi -i "color=c=red:s=WxH:r=25:d=0.12[,format=rgba,geq=...]" -c:v libvpx-vp9 -b:v 0 -crf 30 -pix_fmt yuv420p|yuva420p</c>.
/// </summary>
internal static class NativeFixtures
{
    /// <summary>64×64 opaque red, no alpha.</summary>
    public static byte[] Red64 => Convert.FromBase64String(
        "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAHfEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHGTbuMU6uEElTD" +
        "Z1OsggEMTbuMU6uEHFO7a1OsggHJ7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmoCrXsYMPQkBNgIRMYXZmV0GETGF2ZkSJiEBeAAAAAAAAFlSua8GuAQAAAAAAADjXgQFzxYgAAAAA" +
        "AAAAAZyBACK1nIN1bmSIgQCGhVZfVlA5g4EBI+ODhAJiWgDgibCBQLqBQJqBAhJUw2fVc3PSY8CLY8WIAAAAAAAAAAFnyJxFo4dFTkNPREVSRIePTGF2YyBs" +
        "aWJ2cHgtdnA5Z8iiRaOIRFVSQVRJT05Eh5QwMDowMDowMC4xMjAwMDAwMDAAAB9DtnXe54EAo6+BAACAgkmDQgAD8AP2ADgkHBg+AAAwYAAAZz///pRM////" +
        "/158/////9qAQ6iYAKOTgQAoAIYAQJKcAE8AAANgAABUcKOTgQBQAIYAQJKcAE2gAANgAABUcBxTu2uRu4+zgQC3iveBAfGCAWbwgQM=");

    /// <summary>64×64 red, opaque on the left half (x &lt; 32) and clear on the right, alpha in <c>BlockAdditional</c>.</summary>
    public static byte[] HalfAlpha64 => Convert.FromBase64String(
        "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAJXEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHGTbuMU6uEElTD" +
        "Z1OsggEXTbuMU6uEHFO7a1OsggJB7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmoCrXsYMPQkBNgIRMYXZmV0GETGF2ZkSJiEBeAAAAAAAAFlSua8yuAQAAAAAAAEPXgQFzxYgAAAAA" +
        "AAAAAZyBACK1nIN1bmSIgQCGhVZfVlA5g4EBI+ODhAJiWgDglLCBQLqBQJqBAlPAgQFVsIRVuYEBElTDZ9Vzc9JjwItjxYgAAAAAAAAAAWfInEWjh0VOQ09E" +
        "RVJEh49MYXZjIGxpYnZweC12cDlnyKJFo4hEVVJBVElPTkSHlDAwOjAwOjAwLjEyMDAwMDAwMAAAH0O2dUDK54EAoN+hr4EAAACCSYNCAAPwA/YAOCQcGD4A" +
        "ADBgAABnP//+lEz/////Xnz/////2oBDqJgAdaGrpqnugQGlpIJJg0IAA/AD9gA4JBwYPgAAMGAAACin//+v2Gx///r9DeAAAKCxoZOBACgAhgBAkpwATwAA" +
        "A2AAAFRwdaGWppTugQGlj4YAQJKcAE8AAANgAABUcPuB2KCxoZOBAFAAhgBAkpwATaAAA2AAAFRwdaGWppTugQGlj4YAQJKcAE2gAANgAABUcPuB2BxTu2uR" +
        "u4+zgQC3iveBAfGCAXHwgQM=");

    /// <summary>A 512×512 video sticker: a red square over 156..355 on both axes, clear around it.</summary>
    public static byte[] Square512 => Convert.FromBase64String(
        "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAMBEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHGTbuMU6uEElTD" +
        "Z1OsggEZTbuMU6uEHFO7a1OsggLr7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmoCrXsYMPQkBNgIRMYXZmV0GETGF2ZkSJiEBeAAAAAAAAFlSua86uAQAAAAAAAEXXgQFzxYgAAAAA" +
        "AAAAAZyBACK1nIN1bmSIgQCGhVZfVlA5g4EBI+ODhAJiWgDglrCCAgC6ggIAmoECU8CBAVWwhFW5gQESVMNn1XNz0mPAi2PFiAAAAAAAAAABZ8icRaOHRU5D" +
        "T0RFUkSHj0xhdmMgbGlidnB4LXZwOWfIokWjiERVUkFUSU9ORIeUMDA6MDA6MDAuMTIwMDAwMDAwAAAfQ7Z1QXLngQCgQNih3IEAAACCSYNCAB/wH/YAOCQc" +
        "GD4QAFBh9jr2gFzR7gAAAAAAHGb/1d////Xnz/////2oBDqBWFJHkR4cePHhwABm/9Xf///158/////9qAQ6gVhSR5EeHHjx4cAAdaH3pvXugQGl8IJJg0IA" +
        "H/Af9gA4JBwYPhAAcG+x17QAulX/gB779AAAAAAAIWcb9MRKvnbmWM6oFDKlz+hj8Jn5i6azeHeam9PgCSC4AGcb9MRKvnb7s/t7tK0xHQ+GqCkISQYizj6M" +
        "n+CDVhS2zN9Liujm3hS/HACgy6GhgQAoAIYAQJKcAE8BAAMAYNWFGwAAAAAABGcRzABnEcwAdaGipqDugQGlm4YAQJKcAE8BAAMAYNWFGwAAAAAAA2mlWGml" +
        "WPuB2KDFoZ6BAFAAhgBAkpwATaEAAYBgAAAAAAAEZxHMAGcRzAB1oZ+mne6BAaWYhgBAkpwATaEAAYBgAAAAAAADaaVYaaVY+4HYHFO7a5G7j7OBALeK94EB" +
        "8YIBc/CBAw==");
}
