//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace AccountContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_DeleteAccountResult_Formatter : IonFormatter<DeleteAccountResult>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public DeleteAccountResult Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __success = IonFormatterStorage<bool>.Read(reader);
        var __error = IonFormatterStorage<DeleteAccountError>.Read(reader);
        var __scheduledat = reader.ReadNullable<datetime>();
        var __executionat = reader.ReadNullable<datetime>();
        reader.ReadEndArrayAndSkip(arraySize - 4);
        return new(__success, __error, __scheduledat, __executionat);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, DeleteAccountResult value)
    {
        writer.WriteStartArray(4);
        IonFormatterStorage<bool>.Write(writer, value.success);
        IonFormatterStorage<DeleteAccountError>.Write(writer, value.error);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.scheduledAt);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.executionAt);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CancelDeleteResult_Formatter : IonFormatter<CancelDeleteResult>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CancelDeleteResult Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __success = IonFormatterStorage<bool>.Read(reader);
        var __error = IonFormatterStorage<CancelDeleteError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__success, __error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CancelDeleteResult value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<bool>.Write(writer, value.success);
        IonFormatterStorage<CancelDeleteError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_MeDetails_Formatter : IonFormatter<MeDetails>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public MeDetails Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __gdrpexportinprogress = IonFormatterStorage<bool>.Read(reader);
        var __deletionstatus = IonFormatterStorage<DeletionStatusKind>.Read(reader);
        var __deletionscheduledat = reader.ReadNullable<datetime>();
        var __deletionexecutionat = reader.ReadNullable<datetime>();
        var __avatarfileid = IonFormatterStorage<string>.Read(reader);
        var __userid = IonFormatterStorage<guid>.Read(reader);
        var __displayname = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 7);
        return new(__gdrpexportinprogress, __deletionstatus, __deletionscheduledat, __deletionexecutionat, __avatarfileid, __userid, __displayname);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, MeDetails value)
    {
        writer.WriteStartArray(7);
        IonFormatterStorage<bool>.Write(writer, value.gdrpExportInProgress);
        IonFormatterStorage<DeletionStatusKind>.Write(writer, value.deletionStatus);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.deletionScheduledAt);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.deletionExecutionAt);
        IonFormatterStorage<string>.Write(writer, value.avatarFileId);
        IonFormatterStorage<guid>.Write(writer, value.userId);
        IonFormatterStorage<string>.Write(writer, value.displayName);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_DeleteAccountError_Formatter : IonFormatter<DeleteAccountError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public DeleteAccountError Read(CborReader reader)
    {
         return (DeleteAccountError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, DeleteAccountError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CancelDeleteError_Formatter : IonFormatter<CancelDeleteError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CancelDeleteError Read(CborReader reader)
    {
         return (CancelDeleteError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CancelDeleteError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_RequestExportGDRPStatus_Formatter : IonFormatter<RequestExportGDRPStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public RequestExportGDRPStatus Read(CborReader reader)
    {
         return (RequestExportGDRPStatus)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, RequestExportGDRPStatus value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_DeletionStatusKind_Formatter : IonFormatter<DeletionStatusKind>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public DeletionStatusKind Read(CborReader reader)
    {
         return (DeletionStatusKind)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, DeletionStatusKind value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

