//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace AccountContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
internal static class IonProjectFormatterStorageModuleInit
{
    [ModuleInitializer]
    internal static void Init()
    {
        
      IonFormatterStorage<DeleteAccountResult>.Value = new Ion_DeleteAccountResult_Formatter();
      IonFormatterStorage<CancelDeleteResult>.Value = new Ion_CancelDeleteResult_Formatter();
      IonFormatterStorage<MeDetails>.Value = new Ion_MeDetails_Formatter();
      IonFormatterStorage<DeleteAccountError>.Value = new Ion_DeleteAccountError_Formatter();
      IonFormatterStorage<CancelDeleteError>.Value = new Ion_CancelDeleteError_Formatter();
      IonFormatterStorage<RequestExportGDRPStatus>.Value = new Ion_RequestExportGDRPStatus_Formatter();
      IonFormatterStorage<DeletionStatusKind>.Value = new Ion_DeletionStatusKind_Formatter();
      IonFormatterStorage<AddRedirectResult>.Value = new Ion_AddRedirectResult_Formatter();
      IonFormatterStorage<MyInvitesInfo>.Value = new Ion_MyInvitesInfo_Formatter();
      IonFormatterStorage<TeamInviteInfo>.Value = new Ion_TeamInviteInfo_Formatter();
      IonFormatterStorage<AppDetails>.Value = new Ion_AppDetails_Formatter();
      IonFormatterStorage<ScopeKeyValue>.Value = new Ion_ScopeKeyValue_Formatter();
      IonFormatterStorage<BotDetails>.Value = new Ion_BotDetails_Formatter();
      IonFormatterStorage<ClientAppDetails>.Value = new Ion_ClientAppDetails_Formatter();
      IonFormatterStorage<TeamShortDetails>.Value = new Ion_TeamShortDetails_Formatter();
      IonFormatterStorage<TeamDetails>.Value = new Ion_TeamDetails_Formatter();
      IonFormatterStorage<TeamMemberDetails>.Value = new Ion_TeamMemberDetails_Formatter();
      IonFormatterStorage<ShortUserDetails>.Value = new Ion_ShortUserDetails_Formatter();
      IonFormatterStorage<UploadFileError>.Value = new Ion_UploadFileError_Formatter();
      IonFormatterStorage<InviteUserError>.Value = new Ion_InviteUserError_Formatter();
      IonFormatterStorage<ClientAppPlatform>.Value = new Ion_ClientAppPlatform_Formatter();
      IonFormatterStorage<CheckBotUsernameValid>.Value = new Ion_CheckBotUsernameValid_Formatter();
      IonFormatterStorage<BotLifecycleState>.Value = new Ion_BotLifecycleState_Formatter();
      IonFormatterStorage<AppKind>.Value = new Ion_AppKind_Formatter();
      IonFormatterStorage<IUploadAvatarResult>.Value = new Ion_IUploadAvatarResult_Formatter();
      IonFormatterStorage<SuccessUploadAvatarFile>.Value = new Ion_SuccessUploadAvatarFile_Formatter();
      IonFormatterStorage<FailedUploadAvatarFile>.Value = new Ion_FailedUploadAvatarFile_Formatter();
      IonExecutorMetadataStorage.AddExecutor<Ion_AccountConsole_ServiceExecutor>("IAccountConsole");
      IonExecutorMetadataStorage.AddExecutor<Ion_TeamConsole_ServiceExecutor>("ITeamConsole");
      IonExecutorMetadataStorage.AddExecutor<Ion_AppManagement_ServiceExecutor>("IAppManagement");
      IonExecutorMetadataStorage.AddClient<Ion_AccountConsole_ClientImpl>("IAccountConsole");
      IonExecutorMetadataStorage.AddClient<Ion_TeamConsole_ClientImpl>("ITeamConsole");
      IonExecutorMetadataStorage.AddClient<Ion_AppManagement_ClientImpl>("IAppManagement");

    }
}
