//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace AccountContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record AddRedirectResult(bool ok, string? error);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record MyInvitesInfo(ShortUserDetails from, datetime date, TeamShortDetails team);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record TeamInviteInfo(ShortUserDetails from, ShortUserDetails to, datetime date);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record AppDetails(guid appId, guid teamId, string name, string? desc, BotDetails? botDetails, ClientAppDetails? clientAppDetails, AppKind kind, string clientId, string? clientSecret, string? verificationKey, datetime createdAt, IonArray<ScopeKeyValue> requiredScopes, IonArray<string> allowedRedirects);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ScopeKeyValue(bool isRequired, string key, bool isLocked);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record BotDetails(bool requiresOAuth2, bool requiresArgxAuth, bool allowDMs, bool isVerfied, i4 maxSpaces, string? avatarFileId, string botToken, BotLifecycleState lifecycleState, u8 requiredEntitlements);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ClientAppDetails(ClientAppPlatform platform, bool allowedDevelopmentRegenerateCoockies, bool isPublic, bool isVerfied, string? repositoryUrl, i4 rateLimitPerMinute, string? websiteUrl, bool isInternalApp);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record TeamShortDetails(guid teamId, string name, string avatarFileId, i4 appsCount);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record TeamDetails(guid teamId, guid ownerId, string name, string avatarFileId, IonArray<TeamMemberDetails> members, IonArray<AppDetails> apps);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record TeamMemberDetails(ShortUserDetails user, guid teamId, bool isPending, bool isOwner, IonArray<string> claims, datetime joinedAt);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ShortUserDetails(guid userId, string avatarFileId, string displayName, string username);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum UploadFileError : u4
{
    NONE = 0,
    NOT_AUTHORIZED = 1,
    INTERNAL_ERROR = 2,
}

/// <summary>Open-enum helpers for <see cref="UploadFileError"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_UploadFileError_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this UploadFileError value)
        => value == UploadFileError.NONE || value == UploadFileError.NOT_AUTHORIZED || value == UploadFileError.INTERNAL_ERROR;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this UploadFileError value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum InviteUserError : u4
{
    OK = 0,
    USER_NOT_FOUND = 1,
    ALREADY_INVITED = 2,
    ALREADY_IN_TEAM = 3,
    INTERNAL_ERROR = 4,
}

/// <summary>Open-enum helpers for <see cref="InviteUserError"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_InviteUserError_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this InviteUserError value)
        => value == InviteUserError.OK || value == InviteUserError.USER_NOT_FOUND || value == InviteUserError.ALREADY_INVITED || value == InviteUserError.ALREADY_IN_TEAM || value == InviteUserError.INTERNAL_ERROR;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this InviteUserError value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum ClientAppPlatform : u4
{
    WindowsDesktop = 0,
    MacOSDesktop = 1,
    LinuxDesktop = 2,
    WebBased = 3,
    iOS = 4,
    Android = 5,
}

/// <summary>Open-enum helpers for <see cref="ClientAppPlatform"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_ClientAppPlatform_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this ClientAppPlatform value)
        => value == ClientAppPlatform.WindowsDesktop || value == ClientAppPlatform.MacOSDesktop || value == ClientAppPlatform.LinuxDesktop || value == ClientAppPlatform.WebBased || value == ClientAppPlatform.iOS || value == ClientAppPlatform.Android;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this ClientAppPlatform value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum CheckBotUsernameValid : u4
{
    OK = 0,
    ALREADY_CLAIMED = 1,
    POSTFIX_BOT_REQUIRED = 2,
}

/// <summary>Open-enum helpers for <see cref="CheckBotUsernameValid"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_CheckBotUsernameValid_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this CheckBotUsernameValid value)
        => value == CheckBotUsernameValid.OK || value == CheckBotUsernameValid.ALREADY_CLAIMED || value == CheckBotUsernameValid.POSTFIX_BOT_REQUIRED;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this CheckBotUsernameValid value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum BotLifecycleState : u4
{
    Development = 0,
    Published = 1,
    Suspended = 2,
}

/// <summary>Open-enum helpers for <see cref="BotLifecycleState"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_BotLifecycleState_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this BotLifecycleState value)
        => value == BotLifecycleState.Development || value == BotLifecycleState.Published || value == BotLifecycleState.Suspended;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this BotLifecycleState value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum AppKind : u4
{
    ClientApp = 0,
    BotApp = 1,
    WebApp = 2,
}

/// <summary>Open-enum helpers for <see cref="AppKind"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_AppKind_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this AppKind value)
        => value == AppKind.ClientApp || value == AppKind.BotApp || value == AppKind.WebApp;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this AppKind value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ITeamConsole : IIonService
{
    Task<IonArray<TeamShortDetails>> GetMyTeams(CancellationToken ct = default);
    Task<TeamDetails> GetTeamDetails(guid teamId, CancellationToken ct = default);
    Task<IonArray<TeamInviteInfo>> GetTeamInvites(guid teamId, CancellationToken ct = default);
    Task<TeamDetails> CreateTeam(string name, CancellationToken ct = default);
    Task<InviteUserError> InviteUserToTeam(guid teamId, string username, CancellationToken ct = default);
    Task<IUploadAvatarResult> BeginUploadTeamAvatar(CancellationToken ct = default);
    Task CompleteUploadTeamAvatar(guid blobId, CancellationToken ct = default);
    Task<IonArray<MyInvitesInfo>> GetMyInvites(CancellationToken ct = default);
    Task AcceptTeamInvite(guid teamId, CancellationToken ct = default);
    Task DeclineTeamInvite(guid teamId, CancellationToken ct = default);
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IAppManagement : IIonService
{
    Task<AppDetails> CreateBotApp(guid teamId, string name, string username, CancellationToken ct = default);
    Task<AppDetails> CreateClientApp(guid teamId, string name, ClientAppPlatform platform, CancellationToken ct = default);
    Task EnsureCoockiesForApp(guid teamId, guid appId, CancellationToken ct = default);
    Task<AppDetails> GetAppDetails(guid teamId, guid appId, CancellationToken ct = default);
    Task<string> RegenerateBotToken(guid teamId, guid appId, CancellationToken ct = default);
    Task<CheckBotUsernameValid> CheckUsernameForBot(guid teamId, string username, CancellationToken ct = default);
    Task<IUploadAvatarResult> BeginUploadAppAvatar(guid teamId, CancellationToken ct = default);
    Task CompleteUploadAppAvatar(guid teamId, guid blobId, CancellationToken ct = default);
    Task UpdateScope(guid teamId, guid appId, ScopeKeyValue scope, CancellationToken ct = default);
    Task UpdateRedirects(guid teamId, guid appId, IonArray<string> redirects, CancellationToken ct = default);
    Task<AddRedirectResult> AddRedirect(guid teamId, guid appId, string redirect, CancellationToken ct = default);
    Task RemoveRedirect(guid teamId, guid appId, string redirect, CancellationToken ct = default);
    Task PublishBot(guid teamId, guid appId, CancellationToken ct = default);
    Task UnpublishBot(guid teamId, guid appId, CancellationToken ct = default);
    Task SuspendBot(guid teamId, guid appId, CancellationToken ct = default);
    Task UpdateBotEntitlements(guid teamId, guid appId, u8 entitlements, CancellationToken ct = default);
    Task SetBotOAuth(guid teamId, guid appId, bool enabled, CancellationToken ct = default);
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IUploadAvatarResult : IIonUnion<IUploadAvatarResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessUploadAvatarFile => this is SuccessUploadAvatarFile;

    internal bool IsFailedUploadAvatarFile => this is FailedUploadAvatarFile;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessUploadAvatarFile(guid blobId) : IUploadAvatarResult
{
    public string UnionKey => nameof(SuccessUploadAvatarFile);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedUploadAvatarFile(UploadFileError error) : IUploadAvatarResult
{
    public string UnionKey => nameof(FailedUploadAvatarFile);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IUploadAvatarResult_Formatter : IonFormatter<IUploadAvatarResult>
{
    public IUploadAvatarResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IUploadAvatarResult", 2u);
        IUploadAvatarResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessUploadAvatarFile>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedUploadAvatarFile>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IUploadAvatarResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IUploadAvatarResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessUploadAvatarFile n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessUploadAvatarFile>.Write(writer, n_0);
        }

        else if (value is FailedUploadAvatarFile n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedUploadAvatarFile>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IUploadAvatarResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessUploadAvatarFile_Formatter : IonFormatter<SuccessUploadAvatarFile>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessUploadAvatarFile Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "SuccessUploadAvatarFile");
        var __blobid = IonFormatterStorage<guid>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__blobid);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessUploadAvatarFile value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<guid>.Write(writer, value.blobId);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedUploadAvatarFile_Formatter : IonFormatter<FailedUploadAvatarFile>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedUploadAvatarFile Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedUploadAvatarFile");
        var __error = IonFormatterStorage<UploadFileError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedUploadAvatarFile value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<UploadFileError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}


