//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------
import { 
  CborReader, 
  CborWriter, 
  
  DateOnly, 
  IonDateTime, 
  IonDecimal, 
  Duration, 
  TimeOnly, 
  Guid, 
  
  IonFormatterStorage,

  IonArray,
  IonMaybe,
  IonPartial,

  IIonService,
  IIonUnion,
  
  ServiceExecutor,
  IonClientContext,
  IonRequest,
  IonWsClient,
  IonInterceptor
} from "@argon-chat/ion.webcore";

type guid = Guid;
type timeonly = TimeOnly;
type duration = Duration;
// IonDateTime, never the deprecated `DateTimeOffset { date: Date; offsetMinutes }`
// shape: `Date` is millisecond-resolution, so it cannot hold the 100ns ticks the
// wire form carries, and the webcore "datetime" formatter now reads and writes
// IonDateTime — leaving the old alias here would be a live type mismatch, not just
// a lossy one.
type datetime = IonDateTime;
type decimal = IonDecimal;
type dateonly = DateOnly;

declare type bool = boolean;

declare type i1 = number;
declare type i2 = number;
declare type i4 = number;
declare type i8 = bigint;
declare type i16 = bigint;


declare type u1 = number;
declare type u2 = number;
declare type u4 = number;
declare type u8 = bigint;
declare type u16 = bigint;


declare type f2 = number;
declare type f4 = number;
declare type f8 = number;

export interface DeleteAccountResult {
  success: bool;
  error: DeleteAccountError;
  scheduledAt: datetime | null;
  executionAt: datetime | null;
};


export interface CancelDeleteResult {
  success: bool;
  error: CancelDeleteError;
};


export interface MeDetails {
  gdrpExportInProgress: bool;
  deletionStatus: DeletionStatusKind;
  deletionScheduledAt: datetime | null;
  deletionExecutionAt: datetime | null;
  avatarFileId: string;
  userId: guid;
  displayName: string;
};


export enum DeleteAccountError
{
  None = 0,
  InvalidPassword = 1,
  AlreadyScheduled = 2,
  HasActiveSubscription = 3,
  OwnsSpaces = 4,
  AccountLocked = 5,
  InternalError = 6,
}

const declaredDeleteAccountError: ReadonlySet<unknown> = new Set<unknown>([DeleteAccountError.None, DeleteAccountError.InvalidPassword, DeleteAccountError.AlreadyScheduled, DeleteAccountError.HasActiveSubscription, DeleteAccountError.OwnsSpaces, DeleteAccountError.AccountLocked, DeleteAccountError.InternalError]);

/**
 * Open-enum helpers for {@link DeleteAccountError}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_DeleteAccountError_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: DeleteAccountError): boolean {
    return declaredDeleteAccountError.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: DeleteAccountError): u4 | undefined {
    return declaredDeleteAccountError.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum CancelDeleteError
{
  None = 0,
  NotScheduled = 1,
  AlreadyExecuting = 2,
  AlreadyCompleted = 3,
  InternalError = 4,
}

const declaredCancelDeleteError: ReadonlySet<unknown> = new Set<unknown>([CancelDeleteError.None, CancelDeleteError.NotScheduled, CancelDeleteError.AlreadyExecuting, CancelDeleteError.AlreadyCompleted, CancelDeleteError.InternalError]);

/**
 * Open-enum helpers for {@link CancelDeleteError}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_CancelDeleteError_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: CancelDeleteError): boolean {
    return declaredCancelDeleteError.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: CancelDeleteError): u4 | undefined {
    return declaredCancelDeleteError.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum RequestExportGDRPStatus
{
  Unknown = 0,
  Ok = 1,
  Already = 2,
  RateLimit = 3,
}

const declaredRequestExportGDRPStatus: ReadonlySet<unknown> = new Set<unknown>([RequestExportGDRPStatus.Unknown, RequestExportGDRPStatus.Ok, RequestExportGDRPStatus.Already, RequestExportGDRPStatus.RateLimit]);

/**
 * Open-enum helpers for {@link RequestExportGDRPStatus}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_RequestExportGDRPStatus_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: RequestExportGDRPStatus): boolean {
    return declaredRequestExportGDRPStatus.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: RequestExportGDRPStatus): u4 | undefined {
    return declaredRequestExportGDRPStatus.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum DeletionStatusKind
{
  None = 0,
  Scheduled = 1,
  Executing = 2,
  Completed = 3,
  Failed = 4,
}

const declaredDeletionStatusKind: ReadonlySet<unknown> = new Set<unknown>([DeletionStatusKind.None, DeletionStatusKind.Scheduled, DeletionStatusKind.Executing, DeletionStatusKind.Completed, DeletionStatusKind.Failed]);

/**
 * Open-enum helpers for {@link DeletionStatusKind}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_DeletionStatusKind_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: DeletionStatusKind): boolean {
    return declaredDeletionStatusKind.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: DeletionStatusKind): u4 | undefined {
    return declaredDeletionStatusKind.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export interface AddRedirectResult {
  ok: bool;
  error: string | null;
};


export interface MyInvitesInfo {
  from: ShortUserDetails;
  date: datetime;
  team: TeamShortDetails;
};


export interface TeamInviteInfo {
  from: ShortUserDetails;
  to: ShortUserDetails;
  date: datetime;
};


export interface AppDetails {
  appId: guid;
  teamId: guid;
  name: string;
  desc: string | null;
  botDetails: BotDetails | null;
  clientAppDetails: ClientAppDetails | null;
  kind: AppKind;
  clientId: string;
  clientSecret: string | null;
  verificationKey: string | null;
  createdAt: datetime;
  requiredScopes: IonArray<ScopeKeyValue>;
  allowedRedirects: IonArray<string>;
};


export interface ScopeKeyValue {
  isRequired: bool;
  key: string;
  isLocked: bool;
};


export interface BotDetails {
  requiresOAuth2: bool;
  requiresArgxAuth: bool;
  allowDMs: bool;
  isVerfied: bool;
  maxSpaces: i4;
  avatarFileId: string | null;
  botToken: string;
  lifecycleState: BotLifecycleState;
  requiredEntitlements: u8;
};


export interface ClientAppDetails {
  platform: ClientAppPlatform;
  allowedDevelopmentRegenerateCoockies: bool;
  isPublic: bool;
  isVerfied: bool;
  repositoryUrl: string | null;
  rateLimitPerMinute: i4;
  websiteUrl: string | null;
  isInternalApp: bool;
};


export interface TeamShortDetails {
  teamId: guid;
  name: string;
  avatarFileId: string;
  appsCount: i4;
};


export interface TeamDetails {
  teamId: guid;
  ownerId: guid;
  name: string;
  avatarFileId: string;
  members: IonArray<TeamMemberDetails>;
  apps: IonArray<AppDetails>;
};


export interface TeamMemberDetails {
  user: ShortUserDetails;
  teamId: guid;
  isPending: bool;
  isOwner: bool;
  claims: IonArray<string>;
  joinedAt: datetime;
};


export interface ShortUserDetails {
  userId: guid;
  avatarFileId: string;
  displayName: string;
  username: string;
};


export enum UploadFileError
{
  NONE = 0,
  NOT_AUTHORIZED = 1,
  INTERNAL_ERROR = 2,
}

const declaredUploadFileError: ReadonlySet<unknown> = new Set<unknown>([UploadFileError.NONE, UploadFileError.NOT_AUTHORIZED, UploadFileError.INTERNAL_ERROR]);

/**
 * Open-enum helpers for {@link UploadFileError}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_UploadFileError_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: UploadFileError): boolean {
    return declaredUploadFileError.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: UploadFileError): u4 | undefined {
    return declaredUploadFileError.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum InviteUserError
{
  OK = 0,
  USER_NOT_FOUND = 1,
  ALREADY_INVITED = 2,
  ALREADY_IN_TEAM = 3,
  INTERNAL_ERROR = 4,
}

const declaredInviteUserError: ReadonlySet<unknown> = new Set<unknown>([InviteUserError.OK, InviteUserError.USER_NOT_FOUND, InviteUserError.ALREADY_INVITED, InviteUserError.ALREADY_IN_TEAM, InviteUserError.INTERNAL_ERROR]);

/**
 * Open-enum helpers for {@link InviteUserError}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_InviteUserError_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: InviteUserError): boolean {
    return declaredInviteUserError.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: InviteUserError): u4 | undefined {
    return declaredInviteUserError.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum ClientAppPlatform
{
  WindowsDesktop = 0,
  MacOSDesktop = 1,
  LinuxDesktop = 2,
  WebBased = 3,
  iOS = 4,
  Android = 5,
}

const declaredClientAppPlatform: ReadonlySet<unknown> = new Set<unknown>([ClientAppPlatform.WindowsDesktop, ClientAppPlatform.MacOSDesktop, ClientAppPlatform.LinuxDesktop, ClientAppPlatform.WebBased, ClientAppPlatform.iOS, ClientAppPlatform.Android]);

/**
 * Open-enum helpers for {@link ClientAppPlatform}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_ClientAppPlatform_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: ClientAppPlatform): boolean {
    return declaredClientAppPlatform.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: ClientAppPlatform): u4 | undefined {
    return declaredClientAppPlatform.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum CheckBotUsernameValid
{
  OK = 0,
  ALREADY_CLAIMED = 1,
  POSTFIX_BOT_REQUIRED = 2,
}

const declaredCheckBotUsernameValid: ReadonlySet<unknown> = new Set<unknown>([CheckBotUsernameValid.OK, CheckBotUsernameValid.ALREADY_CLAIMED, CheckBotUsernameValid.POSTFIX_BOT_REQUIRED]);

/**
 * Open-enum helpers for {@link CheckBotUsernameValid}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_CheckBotUsernameValid_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: CheckBotUsernameValid): boolean {
    return declaredCheckBotUsernameValid.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: CheckBotUsernameValid): u4 | undefined {
    return declaredCheckBotUsernameValid.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum BotLifecycleState
{
  Development = 0,
  Published = 1,
  Suspended = 2,
}

const declaredBotLifecycleState: ReadonlySet<unknown> = new Set<unknown>([BotLifecycleState.Development, BotLifecycleState.Published, BotLifecycleState.Suspended]);

/**
 * Open-enum helpers for {@link BotLifecycleState}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_BotLifecycleState_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: BotLifecycleState): boolean {
    return declaredBotLifecycleState.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: BotLifecycleState): u4 | undefined {
    return declaredBotLifecycleState.has(value) ? undefined : (value as unknown as u4);
  },
} as const;


export enum AppKind
{
  ClientApp = 0,
  BotApp = 1,
  WebApp = 2,
}

const declaredAppKind: ReadonlySet<unknown> = new Set<unknown>([AppKind.ClientApp, AppKind.BotApp, AppKind.WebApp]);

/**
 * Open-enum helpers for {@link AppKind}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_AppKind_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: AppKind): boolean {
    return declaredAppKind.has(value);
  },
  /**
   * The raw `u4` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: AppKind): u4 | undefined {
    return declaredAppKind.has(value) ? undefined : (value as unknown as u4);
  },
} as const;



export abstract class IUploadAvatarResult implements IIonUnion<IUploadAvatarResult>
{
  abstract UnionKey: string;
  abstract UnionIndex: number;
  
  
  
  
  public isSuccessUploadAvatarFile(): this is SuccessUploadAvatarFile {
    return this.UnionKey === "SuccessUploadAvatarFile";
  }
  public isFailedUploadAvatarFile(): this is FailedUploadAvatarFile {
    return this.UnionKey === "FailedUploadAvatarFile";
  }

}


export class SuccessUploadAvatarFile extends IUploadAvatarResult
{
  constructor(public blobId: guid) { super(); }

  UnionKey: string = "SuccessUploadAvatarFile";
  UnionIndex: number = 0;
}

export class FailedUploadAvatarFile extends IUploadAvatarResult
{
  constructor(public error: UploadFileError) { super(); }

  UnionKey: string = "FailedUploadAvatarFile";
  UnionIndex: number = 1;
}



IonFormatterStorage.register("IUploadAvatarResult", {
  read(reader: CborReader): IUploadAvatarResult {
    const unionIndex = IonFormatterStorage.readStartUnion(reader, "IUploadAvatarResult", 2);
    let value: IUploadAvatarResult = null as any;

    if (false)
    {}
        else if (unionIndex == 0)
      value = IonFormatterStorage.get<SuccessUploadAvatarFile>("SuccessUploadAvatarFile").read(reader);
    else if (unionIndex == 1)
      value = IonFormatterStorage.get<FailedUploadAvatarFile>("FailedUploadAvatarFile").read(reader);

    else IonFormatterStorage.invalidUnionIndex("IUploadAvatarResult", unionIndex, 2);

    IonFormatterStorage.readEndUnion(reader);
    return value!;
  },
  write(writer: CborWriter, value: IUploadAvatarResult): void {
    writer.writeStartArray(2);
    writer.writeUInt32(value.UnionIndex);
    if (false)
    {}
        else if (value.UnionIndex == 0) {
        IonFormatterStorage.get<SuccessUploadAvatarFile>("SuccessUploadAvatarFile").write(writer, value as SuccessUploadAvatarFile);
    }
    else if (value.UnionIndex == 1) {
        IonFormatterStorage.get<FailedUploadAvatarFile>("FailedUploadAvatarFile").write(writer, value as FailedUploadAvatarFile);
    }
  
    else throw new Error(`Ion union 'IUploadAvatarResult' has no case ${value.UnionIndex}; this revision declares 2 case(s)`);
    writer.writeEndArray();
  }
});


IonFormatterStorage.register("SuccessUploadAvatarFile", {
  read(reader: CborReader): SuccessUploadAvatarFile {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "SuccessUploadAvatarFile");
    const blobId = IonFormatterStorage.get<guid>('guid').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return new SuccessUploadAvatarFile(blobId);
  },
  write(writer: CborWriter, value: SuccessUploadAvatarFile): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<guid>('guid').write(writer, value.blobId);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("FailedUploadAvatarFile", {
  read(reader: CborReader): FailedUploadAvatarFile {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "FailedUploadAvatarFile");
    const error = IonFormatterStorage.get<UploadFileError>('UploadFileError').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return new FailedUploadAvatarFile(error);
  },
  write(writer: CborWriter, value: FailedUploadAvatarFile): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<UploadFileError>('UploadFileError').write(writer, value.error);
    writer.writeEndArray();
  }
});



IonFormatterStorage.register("DeleteAccountError", {
  read(reader: CborReader): DeleteAccountError {
    return IonFormatterStorage.readOpenEnum<DeleteAccountError>(reader, 'u4');
  },
  write(writer: CborWriter, value: DeleteAccountError): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("DeleteAccountResult", {
  read(reader: CborReader): DeleteAccountResult {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 4, "DeleteAccountResult");
    const success = IonFormatterStorage.get<bool>('bool').read(reader);
    const error = IonFormatterStorage.get<DeleteAccountError>('DeleteAccountError').read(reader);
    const scheduledAt = IonFormatterStorage.readNullable<datetime>(reader, 'datetime');
    const executionAt = IonFormatterStorage.readNullable<datetime>(reader, 'datetime');
    reader.readEndArrayAndSkip(arraySize - 4);
    return { success, error, scheduledAt, executionAt };
  },
  write(writer: CborWriter, value: DeleteAccountResult): void {
    writer.writeStartArray(4);
    IonFormatterStorage.get<bool>('bool').write(writer, value.success);
    IonFormatterStorage.get<DeleteAccountError>('DeleteAccountError').write(writer, value.error);
    IonFormatterStorage.writeNullable<datetime>(writer, value.scheduledAt, 'datetime');
    IonFormatterStorage.writeNullable<datetime>(writer, value.executionAt, 'datetime');
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("CancelDeleteError", {
  read(reader: CborReader): CancelDeleteError {
    return IonFormatterStorage.readOpenEnum<CancelDeleteError>(reader, 'u4');
  },
  write(writer: CborWriter, value: CancelDeleteError): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("CancelDeleteResult", {
  read(reader: CborReader): CancelDeleteResult {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "CancelDeleteResult");
    const success = IonFormatterStorage.get<bool>('bool').read(reader);
    const error = IonFormatterStorage.get<CancelDeleteError>('CancelDeleteError').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { success, error };
  },
  write(writer: CborWriter, value: CancelDeleteResult): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<bool>('bool').write(writer, value.success);
    IonFormatterStorage.get<CancelDeleteError>('CancelDeleteError').write(writer, value.error);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("DeletionStatusKind", {
  read(reader: CborReader): DeletionStatusKind {
    return IonFormatterStorage.readOpenEnum<DeletionStatusKind>(reader, 'u4');
  },
  write(writer: CborWriter, value: DeletionStatusKind): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("MeDetails", {
  read(reader: CborReader): MeDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 7, "MeDetails");
    const gdrpExportInProgress = IonFormatterStorage.get<bool>('bool').read(reader);
    const deletionStatus = IonFormatterStorage.get<DeletionStatusKind>('DeletionStatusKind').read(reader);
    const deletionScheduledAt = IonFormatterStorage.readNullable<datetime>(reader, 'datetime');
    const deletionExecutionAt = IonFormatterStorage.readNullable<datetime>(reader, 'datetime');
    const avatarFileId = IonFormatterStorage.get<string>('string').read(reader);
    const userId = IonFormatterStorage.get<guid>('guid').read(reader);
    const displayName = IonFormatterStorage.get<string>('string').read(reader);
    reader.readEndArrayAndSkip(arraySize - 7);
    return { gdrpExportInProgress, deletionStatus, deletionScheduledAt, deletionExecutionAt, avatarFileId, userId, displayName };
  },
  write(writer: CborWriter, value: MeDetails): void {
    writer.writeStartArray(7);
    IonFormatterStorage.get<bool>('bool').write(writer, value.gdrpExportInProgress);
    IonFormatterStorage.get<DeletionStatusKind>('DeletionStatusKind').write(writer, value.deletionStatus);
    IonFormatterStorage.writeNullable<datetime>(writer, value.deletionScheduledAt, 'datetime');
    IonFormatterStorage.writeNullable<datetime>(writer, value.deletionExecutionAt, 'datetime');
    IonFormatterStorage.get<string>('string').write(writer, value.avatarFileId);
    IonFormatterStorage.get<guid>('guid').write(writer, value.userId);
    IonFormatterStorage.get<string>('string').write(writer, value.displayName);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("RequestExportGDRPStatus", {
  read(reader: CborReader): RequestExportGDRPStatus {
    return IonFormatterStorage.readOpenEnum<RequestExportGDRPStatus>(reader, 'u4');
  },
  write(writer: CborWriter, value: RequestExportGDRPStatus): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("AddRedirectResult", {
  read(reader: CborReader): AddRedirectResult {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "AddRedirectResult");
    const ok = IonFormatterStorage.get<bool>('bool').read(reader);
    const error = IonFormatterStorage.readNullable<string>(reader, 'string');
    reader.readEndArrayAndSkip(arraySize - 2);
    return { ok, error };
  },
  write(writer: CborWriter, value: AddRedirectResult): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<bool>('bool').write(writer, value.ok);
    IonFormatterStorage.writeNullable<string>(writer, value.error, 'string');
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("ShortUserDetails", {
  read(reader: CborReader): ShortUserDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 4, "ShortUserDetails");
    const userId = IonFormatterStorage.get<guid>('guid').read(reader);
    const avatarFileId = IonFormatterStorage.get<string>('string').read(reader);
    const displayName = IonFormatterStorage.get<string>('string').read(reader);
    const username = IonFormatterStorage.get<string>('string').read(reader);
    reader.readEndArrayAndSkip(arraySize - 4);
    return { userId, avatarFileId, displayName, username };
  },
  write(writer: CborWriter, value: ShortUserDetails): void {
    writer.writeStartArray(4);
    IonFormatterStorage.get<guid>('guid').write(writer, value.userId);
    IonFormatterStorage.get<string>('string').write(writer, value.avatarFileId);
    IonFormatterStorage.get<string>('string').write(writer, value.displayName);
    IonFormatterStorage.get<string>('string').write(writer, value.username);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TeamShortDetails", {
  read(reader: CborReader): TeamShortDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 4, "TeamShortDetails");
    const teamId = IonFormatterStorage.get<guid>('guid').read(reader);
    const name = IonFormatterStorage.get<string>('string').read(reader);
    const avatarFileId = IonFormatterStorage.get<string>('string').read(reader);
    const appsCount = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 4);
    return { teamId, name, avatarFileId, appsCount };
  },
  write(writer: CborWriter, value: TeamShortDetails): void {
    writer.writeStartArray(4);
    IonFormatterStorage.get<guid>('guid').write(writer, value.teamId);
    IonFormatterStorage.get<string>('string').write(writer, value.name);
    IonFormatterStorage.get<string>('string').write(writer, value.avatarFileId);
    IonFormatterStorage.get<i4>('i4').write(writer, value.appsCount);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("MyInvitesInfo", {
  read(reader: CborReader): MyInvitesInfo {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "MyInvitesInfo");
    const from = IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').read(reader);
    const date = IonFormatterStorage.get<datetime>('datetime').read(reader);
    const team = IonFormatterStorage.get<TeamShortDetails>('TeamShortDetails').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return { from, date, team };
  },
  write(writer: CborWriter, value: MyInvitesInfo): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').write(writer, value.from);
    IonFormatterStorage.get<datetime>('datetime').write(writer, value.date);
    IonFormatterStorage.get<TeamShortDetails>('TeamShortDetails').write(writer, value.team);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TeamInviteInfo", {
  read(reader: CborReader): TeamInviteInfo {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "TeamInviteInfo");
    const from = IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').read(reader);
    const to = IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').read(reader);
    const date = IonFormatterStorage.get<datetime>('datetime').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return { from, to, date };
  },
  write(writer: CborWriter, value: TeamInviteInfo): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').write(writer, value.from);
    IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').write(writer, value.to);
    IonFormatterStorage.get<datetime>('datetime').write(writer, value.date);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("AppKind", {
  read(reader: CborReader): AppKind {
    return IonFormatterStorage.readOpenEnum<AppKind>(reader, 'u4');
  },
  write(writer: CborWriter, value: AppKind): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("AppDetails", {
  read(reader: CborReader): AppDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 13, "AppDetails");
    const appId = IonFormatterStorage.get<guid>('guid').read(reader);
    const teamId = IonFormatterStorage.get<guid>('guid').read(reader);
    const name = IonFormatterStorage.get<string>('string').read(reader);
    const desc = IonFormatterStorage.readNullable<string>(reader, 'string');
    const botDetails = IonFormatterStorage.readNullable<BotDetails>(reader, 'BotDetails');
    const clientAppDetails = IonFormatterStorage.readNullable<ClientAppDetails>(reader, 'ClientAppDetails');
    const kind = IonFormatterStorage.get<AppKind>('AppKind').read(reader);
    const clientId = IonFormatterStorage.get<string>('string').read(reader);
    const clientSecret = IonFormatterStorage.readNullable<string>(reader, 'string');
    const verificationKey = IonFormatterStorage.readNullable<string>(reader, 'string');
    const createdAt = IonFormatterStorage.get<datetime>('datetime').read(reader);
    const requiredScopes = IonFormatterStorage.readArray<ScopeKeyValue>(reader, 'ScopeKeyValue');
    const allowedRedirects = IonFormatterStorage.readArray<string>(reader, 'string');
    reader.readEndArrayAndSkip(arraySize - 13);
    return { appId, teamId, name, desc, botDetails, clientAppDetails, kind, clientId, clientSecret, verificationKey, createdAt, requiredScopes, allowedRedirects };
  },
  write(writer: CborWriter, value: AppDetails): void {
    writer.writeStartArray(13);
    IonFormatterStorage.get<guid>('guid').write(writer, value.appId);
    IonFormatterStorage.get<guid>('guid').write(writer, value.teamId);
    IonFormatterStorage.get<string>('string').write(writer, value.name);
    IonFormatterStorage.writeNullable<string>(writer, value.desc, 'string');
    IonFormatterStorage.writeNullable<BotDetails>(writer, value.botDetails, 'BotDetails');
    IonFormatterStorage.writeNullable<ClientAppDetails>(writer, value.clientAppDetails, 'ClientAppDetails');
    IonFormatterStorage.get<AppKind>('AppKind').write(writer, value.kind);
    IonFormatterStorage.get<string>('string').write(writer, value.clientId);
    IonFormatterStorage.writeNullable<string>(writer, value.clientSecret, 'string');
    IonFormatterStorage.writeNullable<string>(writer, value.verificationKey, 'string');
    IonFormatterStorage.get<datetime>('datetime').write(writer, value.createdAt);
    IonFormatterStorage.writeArray<ScopeKeyValue>(writer, value.requiredScopes, 'ScopeKeyValue');
    IonFormatterStorage.writeArray<string>(writer, value.allowedRedirects, 'string');
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("ScopeKeyValue", {
  read(reader: CborReader): ScopeKeyValue {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "ScopeKeyValue");
    const isRequired = IonFormatterStorage.get<bool>('bool').read(reader);
    const key = IonFormatterStorage.get<string>('string').read(reader);
    const isLocked = IonFormatterStorage.get<bool>('bool').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return { isRequired, key, isLocked };
  },
  write(writer: CborWriter, value: ScopeKeyValue): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<bool>('bool').write(writer, value.isRequired);
    IonFormatterStorage.get<string>('string').write(writer, value.key);
    IonFormatterStorage.get<bool>('bool').write(writer, value.isLocked);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("BotLifecycleState", {
  read(reader: CborReader): BotLifecycleState {
    return IonFormatterStorage.readOpenEnum<BotLifecycleState>(reader, 'u4');
  },
  write(writer: CborWriter, value: BotLifecycleState): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("BotDetails", {
  read(reader: CborReader): BotDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 9, "BotDetails");
    const requiresOAuth2 = IonFormatterStorage.get<bool>('bool').read(reader);
    const requiresArgxAuth = IonFormatterStorage.get<bool>('bool').read(reader);
    const allowDMs = IonFormatterStorage.get<bool>('bool').read(reader);
    const isVerfied = IonFormatterStorage.get<bool>('bool').read(reader);
    const maxSpaces = IonFormatterStorage.get<i4>('i4').read(reader);
    const avatarFileId = IonFormatterStorage.readNullable<string>(reader, 'string');
    const botToken = IonFormatterStorage.get<string>('string').read(reader);
    const lifecycleState = IonFormatterStorage.get<BotLifecycleState>('BotLifecycleState').read(reader);
    const requiredEntitlements = IonFormatterStorage.get<u8>('u8').read(reader);
    reader.readEndArrayAndSkip(arraySize - 9);
    return { requiresOAuth2, requiresArgxAuth, allowDMs, isVerfied, maxSpaces, avatarFileId, botToken, lifecycleState, requiredEntitlements };
  },
  write(writer: CborWriter, value: BotDetails): void {
    writer.writeStartArray(9);
    IonFormatterStorage.get<bool>('bool').write(writer, value.requiresOAuth2);
    IonFormatterStorage.get<bool>('bool').write(writer, value.requiresArgxAuth);
    IonFormatterStorage.get<bool>('bool').write(writer, value.allowDMs);
    IonFormatterStorage.get<bool>('bool').write(writer, value.isVerfied);
    IonFormatterStorage.get<i4>('i4').write(writer, value.maxSpaces);
    IonFormatterStorage.writeNullable<string>(writer, value.avatarFileId, 'string');
    IonFormatterStorage.get<string>('string').write(writer, value.botToken);
    IonFormatterStorage.get<BotLifecycleState>('BotLifecycleState').write(writer, value.lifecycleState);
    IonFormatterStorage.get<u8>('u8').write(writer, value.requiredEntitlements);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("ClientAppPlatform", {
  read(reader: CborReader): ClientAppPlatform {
    return IonFormatterStorage.readOpenEnum<ClientAppPlatform>(reader, 'u4');
  },
  write(writer: CborWriter, value: ClientAppPlatform): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("ClientAppDetails", {
  read(reader: CborReader): ClientAppDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 8, "ClientAppDetails");
    const platform = IonFormatterStorage.get<ClientAppPlatform>('ClientAppPlatform').read(reader);
    const allowedDevelopmentRegenerateCoockies = IonFormatterStorage.get<bool>('bool').read(reader);
    const isPublic = IonFormatterStorage.get<bool>('bool').read(reader);
    const isVerfied = IonFormatterStorage.get<bool>('bool').read(reader);
    const repositoryUrl = IonFormatterStorage.readNullable<string>(reader, 'string');
    const rateLimitPerMinute = IonFormatterStorage.get<i4>('i4').read(reader);
    const websiteUrl = IonFormatterStorage.readNullable<string>(reader, 'string');
    const isInternalApp = IonFormatterStorage.get<bool>('bool').read(reader);
    reader.readEndArrayAndSkip(arraySize - 8);
    return { platform, allowedDevelopmentRegenerateCoockies, isPublic, isVerfied, repositoryUrl, rateLimitPerMinute, websiteUrl, isInternalApp };
  },
  write(writer: CborWriter, value: ClientAppDetails): void {
    writer.writeStartArray(8);
    IonFormatterStorage.get<ClientAppPlatform>('ClientAppPlatform').write(writer, value.platform);
    IonFormatterStorage.get<bool>('bool').write(writer, value.allowedDevelopmentRegenerateCoockies);
    IonFormatterStorage.get<bool>('bool').write(writer, value.isPublic);
    IonFormatterStorage.get<bool>('bool').write(writer, value.isVerfied);
    IonFormatterStorage.writeNullable<string>(writer, value.repositoryUrl, 'string');
    IonFormatterStorage.get<i4>('i4').write(writer, value.rateLimitPerMinute);
    IonFormatterStorage.writeNullable<string>(writer, value.websiteUrl, 'string');
    IonFormatterStorage.get<bool>('bool').write(writer, value.isInternalApp);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TeamDetails", {
  read(reader: CborReader): TeamDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 6, "TeamDetails");
    const teamId = IonFormatterStorage.get<guid>('guid').read(reader);
    const ownerId = IonFormatterStorage.get<guid>('guid').read(reader);
    const name = IonFormatterStorage.get<string>('string').read(reader);
    const avatarFileId = IonFormatterStorage.get<string>('string').read(reader);
    const members = IonFormatterStorage.readArray<TeamMemberDetails>(reader, 'TeamMemberDetails');
    const apps = IonFormatterStorage.readArray<AppDetails>(reader, 'AppDetails');
    reader.readEndArrayAndSkip(arraySize - 6);
    return { teamId, ownerId, name, avatarFileId, members, apps };
  },
  write(writer: CborWriter, value: TeamDetails): void {
    writer.writeStartArray(6);
    IonFormatterStorage.get<guid>('guid').write(writer, value.teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, value.ownerId);
    IonFormatterStorage.get<string>('string').write(writer, value.name);
    IonFormatterStorage.get<string>('string').write(writer, value.avatarFileId);
    IonFormatterStorage.writeArray<TeamMemberDetails>(writer, value.members, 'TeamMemberDetails');
    IonFormatterStorage.writeArray<AppDetails>(writer, value.apps, 'AppDetails');
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TeamMemberDetails", {
  read(reader: CborReader): TeamMemberDetails {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 6, "TeamMemberDetails");
    const user = IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').read(reader);
    const teamId = IonFormatterStorage.get<guid>('guid').read(reader);
    const isPending = IonFormatterStorage.get<bool>('bool').read(reader);
    const isOwner = IonFormatterStorage.get<bool>('bool').read(reader);
    const claims = IonFormatterStorage.readArray<string>(reader, 'string');
    const joinedAt = IonFormatterStorage.get<datetime>('datetime').read(reader);
    reader.readEndArrayAndSkip(arraySize - 6);
    return { user, teamId, isPending, isOwner, claims, joinedAt };
  },
  write(writer: CborWriter, value: TeamMemberDetails): void {
    writer.writeStartArray(6);
    IonFormatterStorage.get<ShortUserDetails>('ShortUserDetails').write(writer, value.user);
    IonFormatterStorage.get<guid>('guid').write(writer, value.teamId);
    IonFormatterStorage.get<bool>('bool').write(writer, value.isPending);
    IonFormatterStorage.get<bool>('bool').write(writer, value.isOwner);
    IonFormatterStorage.writeArray<string>(writer, value.claims, 'string');
    IonFormatterStorage.get<datetime>('datetime').write(writer, value.joinedAt);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("UploadFileError", {
  read(reader: CborReader): UploadFileError {
    return IonFormatterStorage.readOpenEnum<UploadFileError>(reader, 'u4');
  },
  write(writer: CborWriter, value: UploadFileError): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("InviteUserError", {
  read(reader: CborReader): InviteUserError {
    return IonFormatterStorage.readOpenEnum<InviteUserError>(reader, 'u4');
  },
  write(writer: CborWriter, value: InviteUserError): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});

IonFormatterStorage.register("CheckBotUsernameValid", {
  read(reader: CborReader): CheckBotUsernameValid {
    return IonFormatterStorage.readOpenEnum<CheckBotUsernameValid>(reader, 'u4');
  },
  write(writer: CborWriter, value: CheckBotUsernameValid): void {
    const casted: u4 = value;
    IonFormatterStorage.get<u4>('u4').write(writer, casted);
  }
});




export interface IAccountConsole extends IIonService
{
  GetMe(): Promise<MeDetails>;
  RequestDeleteAccount(password: string): Promise<DeleteAccountResult>;
  CancelDeleteAccount(): Promise<CancelDeleteResult>;
  RequestExportGDRP(): Promise<RequestExportGDRPStatus>;
}




export interface ITeamConsole extends IIonService
{
  GetMyTeams(): Promise<IonArray<TeamShortDetails>>;
  GetTeamDetails(teamId: guid): Promise<TeamDetails>;
  GetTeamInvites(teamId: guid): Promise<IonArray<TeamInviteInfo>>;
  CreateTeam(name: string): Promise<TeamDetails>;
  InviteUserToTeam(teamId: guid, username: string): Promise<InviteUserError>;
  BeginUploadTeamAvatar(): Promise<IUploadAvatarResult>;
  CompleteUploadTeamAvatar(blobId: guid): Promise<void>;
  GetMyInvites(): Promise<IonArray<MyInvitesInfo>>;
  AcceptTeamInvite(teamId: guid): Promise<void>;
  DeclineTeamInvite(teamId: guid): Promise<void>;
}


export interface IAppManagement extends IIonService
{
  CreateBotApp(teamId: guid, name: string, username: string): Promise<AppDetails>;
  CreateClientApp(teamId: guid, name: string, platform: ClientAppPlatform): Promise<AppDetails>;
  EnsureCoockiesForApp(teamId: guid, appId: guid): Promise<void>;
  GetAppDetails(teamId: guid, appId: guid): Promise<AppDetails>;
  RegenerateBotToken(teamId: guid, appId: guid): Promise<string>;
  CheckUsernameForBot(teamId: guid, username: string): Promise<CheckBotUsernameValid>;
  BeginUploadAppAvatar(teamId: guid): Promise<IUploadAvatarResult>;
  CompleteUploadAppAvatar(teamId: guid, blobId: guid): Promise<void>;
  UpdateScope(teamId: guid, appId: guid, scope: ScopeKeyValue): Promise<void>;
  UpdateRedirects(teamId: guid, appId: guid, redirects: IonArray<string>): Promise<void>;
  AddRedirect(teamId: guid, appId: guid, redirect: string): Promise<AddRedirectResult>;
  RemoveRedirect(teamId: guid, appId: guid, redirect: string): Promise<void>;
  PublishBot(teamId: guid, appId: guid): Promise<void>;
  UnpublishBot(teamId: guid, appId: guid): Promise<void>;
  SuspendBot(teamId: guid, appId: guid): Promise<void>;
  UpdateBotEntitlements(teamId: guid, appId: guid, entitlements: u8): Promise<void>;
  SetBotOAuth(teamId: guid, appId: guid, enabled: bool): Promise<void>;
}




export interface IAccountConsole extends IIonService
{
  GetMe(): Promise<MeDetails>;
  RequestDeleteAccount(password: string): Promise<DeleteAccountResult>;
  CancelDeleteAccount(): Promise<CancelDeleteResult>;
  RequestExportGDRP(): Promise<RequestExportGDRPStatus>;
}




export interface ITeamConsole extends IIonService
{
  GetMyTeams(): Promise<IonArray<TeamShortDetails>>;
  GetTeamDetails(teamId: guid): Promise<TeamDetails>;
  GetTeamInvites(teamId: guid): Promise<IonArray<TeamInviteInfo>>;
  CreateTeam(name: string): Promise<TeamDetails>;
  InviteUserToTeam(teamId: guid, username: string): Promise<InviteUserError>;
  BeginUploadTeamAvatar(): Promise<IUploadAvatarResult>;
  CompleteUploadTeamAvatar(blobId: guid): Promise<void>;
  GetMyInvites(): Promise<IonArray<MyInvitesInfo>>;
  AcceptTeamInvite(teamId: guid): Promise<void>;
  DeclineTeamInvite(teamId: guid): Promise<void>;
}


export interface IAppManagement extends IIonService
{
  CreateBotApp(teamId: guid, name: string, username: string): Promise<AppDetails>;
  CreateClientApp(teamId: guid, name: string, platform: ClientAppPlatform): Promise<AppDetails>;
  EnsureCoockiesForApp(teamId: guid, appId: guid): Promise<void>;
  GetAppDetails(teamId: guid, appId: guid): Promise<AppDetails>;
  RegenerateBotToken(teamId: guid, appId: guid): Promise<string>;
  CheckUsernameForBot(teamId: guid, username: string): Promise<CheckBotUsernameValid>;
  BeginUploadAppAvatar(teamId: guid): Promise<IUploadAvatarResult>;
  CompleteUploadAppAvatar(teamId: guid, blobId: guid): Promise<void>;
  UpdateScope(teamId: guid, appId: guid, scope: ScopeKeyValue): Promise<void>;
  UpdateRedirects(teamId: guid, appId: guid, redirects: IonArray<string>): Promise<void>;
  AddRedirect(teamId: guid, appId: guid, redirect: string): Promise<AddRedirectResult>;
  RemoveRedirect(teamId: guid, appId: guid, redirect: string): Promise<void>;
  PublishBot(teamId: guid, appId: guid): Promise<void>;
  UnpublishBot(teamId: guid, appId: guid): Promise<void>;
  SuspendBot(teamId: guid, appId: guid): Promise<void>;
  UpdateBotEntitlements(teamId: guid, appId: guid, entitlements: u8): Promise<void>;
  SetBotOAuth(teamId: guid, appId: guid, enabled: bool): Promise<void>;
}



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

export class AccountConsole_Executor extends ServiceExecutor<IAccountConsole> implements IAccountConsole {
  constructor(public ctx: IonClientContext, private signal: AbortSignal) {
      super();
  }

  
  async GetMe(): Promise<MeDetails> {
    const req = new IonRequest(this.ctx, "IAccountConsole", "GetMe");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(0);
          
    
      
    writer.writeEndArray();
          
    return await req.callAsyncT<MeDetails>("MeDetails", writer.data, this.signal);
  }
  async RequestDeleteAccount(password: string): Promise<DeleteAccountResult> {
    const req = new IonRequest(this.ctx, "IAccountConsole", "RequestDeleteAccount");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<string>('string').write(writer, password);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<DeleteAccountResult>("DeleteAccountResult", writer.data, this.signal);
  }
  async CancelDeleteAccount(): Promise<CancelDeleteResult> {
    const req = new IonRequest(this.ctx, "IAccountConsole", "CancelDeleteAccount");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(0);
          
    
      
    writer.writeEndArray();
          
    return await req.callAsyncT<CancelDeleteResult>("CancelDeleteResult", writer.data, this.signal);
  }
  async RequestExportGDRP(): Promise<RequestExportGDRPStatus> {
    const req = new IonRequest(this.ctx, "IAccountConsole", "RequestExportGDRP");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(0);
          
    
      
    writer.writeEndArray();
          
    return await req.callAsyncT<RequestExportGDRPStatus>("RequestExportGDRPStatus", writer.data, this.signal);
  }

}

IonFormatterStorage.registerClientExecutor<IAccountConsole>('AccountConsole', AccountConsole_Executor);

export class TeamConsole_Executor extends ServiceExecutor<ITeamConsole> implements ITeamConsole {
  constructor(public ctx: IonClientContext, private signal: AbortSignal) {
      super();
  }

  
  async GetMyTeams(): Promise<IonArray<TeamShortDetails>> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "GetMyTeams");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(0);
          
    
      
    writer.writeEndArray();
          
    return await req.callAsyncT<IonArray<TeamShortDetails>>("IonArray<TeamShortDetails>", writer.data, this.signal);
  }
  async GetTeamDetails(teamId: guid): Promise<TeamDetails> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "GetTeamDetails");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<TeamDetails>("TeamDetails", writer.data, this.signal);
  }
  async GetTeamInvites(teamId: guid): Promise<IonArray<TeamInviteInfo>> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "GetTeamInvites");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<IonArray<TeamInviteInfo>>("IonArray<TeamInviteInfo>", writer.data, this.signal);
  }
  async CreateTeam(name: string): Promise<TeamDetails> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "CreateTeam");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<string>('string').write(writer, name);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<TeamDetails>("TeamDetails", writer.data, this.signal);
  }
  async InviteUserToTeam(teamId: guid, username: string): Promise<InviteUserError> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "InviteUserToTeam");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<string>('string').write(writer, username);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<InviteUserError>("InviteUserError", writer.data, this.signal);
  }
  async BeginUploadTeamAvatar(): Promise<IUploadAvatarResult> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "BeginUploadTeamAvatar");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(0);
          
    
      
    writer.writeEndArray();
          
    return await req.callAsyncT<IUploadAvatarResult>("IUploadAvatarResult", writer.data, this.signal);
  }
  async CompleteUploadTeamAvatar(blobId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "CompleteUploadTeamAvatar");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<guid>('guid').write(writer, blobId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async GetMyInvites(): Promise<IonArray<MyInvitesInfo>> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "GetMyInvites");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(0);
          
    
      
    writer.writeEndArray();
          
    return await req.callAsyncT<IonArray<MyInvitesInfo>>("IonArray<MyInvitesInfo>", writer.data, this.signal);
  }
  async AcceptTeamInvite(teamId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "AcceptTeamInvite");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async DeclineTeamInvite(teamId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "ITeamConsole", "DeclineTeamInvite");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }

}

IonFormatterStorage.registerClientExecutor<ITeamConsole>('TeamConsole', TeamConsole_Executor);

export class AppManagement_Executor extends ServiceExecutor<IAppManagement> implements IAppManagement {
  constructor(public ctx: IonClientContext, private signal: AbortSignal) {
      super();
  }

  
  async CreateBotApp(teamId: guid, name: string, username: string): Promise<AppDetails> {
    const req = new IonRequest(this.ctx, "IAppManagement", "CreateBotApp");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<string>('string').write(writer, name);
    IonFormatterStorage.get<string>('string').write(writer, username);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<AppDetails>("AppDetails", writer.data, this.signal);
  }
  async CreateClientApp(teamId: guid, name: string, platform: ClientAppPlatform): Promise<AppDetails> {
    const req = new IonRequest(this.ctx, "IAppManagement", "CreateClientApp");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<string>('string').write(writer, name);
    IonFormatterStorage.get<ClientAppPlatform>('ClientAppPlatform').write(writer, platform);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<AppDetails>("AppDetails", writer.data, this.signal);
  }
  async EnsureCoockiesForApp(teamId: guid, appId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "EnsureCoockiesForApp");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async GetAppDetails(teamId: guid, appId: guid): Promise<AppDetails> {
    const req = new IonRequest(this.ctx, "IAppManagement", "GetAppDetails");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<AppDetails>("AppDetails", writer.data, this.signal);
  }
  async RegenerateBotToken(teamId: guid, appId: guid): Promise<string> {
    const req = new IonRequest(this.ctx, "IAppManagement", "RegenerateBotToken");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<string>("string", writer.data, this.signal);
  }
  async CheckUsernameForBot(teamId: guid, username: string): Promise<CheckBotUsernameValid> {
    const req = new IonRequest(this.ctx, "IAppManagement", "CheckUsernameForBot");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<string>('string').write(writer, username);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<CheckBotUsernameValid>("CheckBotUsernameValid", writer.data, this.signal);
  }
  async BeginUploadAppAvatar(teamId: guid): Promise<IUploadAvatarResult> {
    const req = new IonRequest(this.ctx, "IAppManagement", "BeginUploadAppAvatar");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<IUploadAvatarResult>("IUploadAvatarResult", writer.data, this.signal);
  }
  async CompleteUploadAppAvatar(teamId: guid, blobId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "CompleteUploadAppAvatar");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, blobId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async UpdateScope(teamId: guid, appId: guid, scope: ScopeKeyValue): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "UpdateScope");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
    IonFormatterStorage.get<ScopeKeyValue>('ScopeKeyValue').write(writer, scope);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async UpdateRedirects(teamId: guid, appId: guid, redirects: IonArray<string>): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "UpdateRedirects");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
    IonFormatterStorage.writeArray<string>(writer, redirects, 'string');
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async AddRedirect(teamId: guid, appId: guid, redirect: string): Promise<AddRedirectResult> {
    const req = new IonRequest(this.ctx, "IAppManagement", "AddRedirect");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
    IonFormatterStorage.get<string>('string').write(writer, redirect);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<AddRedirectResult>("AddRedirectResult", writer.data, this.signal);
  }
  async RemoveRedirect(teamId: guid, appId: guid, redirect: string): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "RemoveRedirect");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
    IonFormatterStorage.get<string>('string').write(writer, redirect);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async PublishBot(teamId: guid, appId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "PublishBot");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async UnpublishBot(teamId: guid, appId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "UnpublishBot");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async SuspendBot(teamId: guid, appId: guid): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "SuspendBot");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async UpdateBotEntitlements(teamId: guid, appId: guid, entitlements: u8): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "UpdateBotEntitlements");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
    IonFormatterStorage.get<u8>('u8').write(writer, entitlements);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }
  async SetBotOAuth(teamId: guid, appId: guid, enabled: bool): Promise<void> {
    const req = new IonRequest(this.ctx, "IAppManagement", "SetBotOAuth");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(3);
          
    IonFormatterStorage.get<guid>('guid').write(writer, teamId);
    IonFormatterStorage.get<guid>('guid').write(writer, appId);
    IonFormatterStorage.get<bool>('bool').write(writer, enabled);
      
    writer.writeEndArray();
          
    await req.callAsync(writer.data, this.signal);
  }

}

IonFormatterStorage.registerClientExecutor<IAppManagement>('AppManagement', AppManagement_Executor);


export function createClient(endpoint: string, interceptors: IonInterceptor[]) {
  const ctx = {
    baseUrl: endpoint,
    interceptors: interceptors
  } as IonClientContext;
  const controller = new AbortController();

  return new Proxy(
    {},
    {
      get(_target, propKey) {
        if (typeof propKey !== "string") return undefined;
        if (propKey === "AccountConsole") return IonFormatterStorage.createExecutor("AccountConsole", ctx, controller.signal);
        if (propKey === "TeamConsole") return IonFormatterStorage.createExecutor("TeamConsole", ctx, controller.signal);
        if (propKey === "AppManagement") return IonFormatterStorage.createExecutor("AppManagement", ctx, controller.signal);


        throw new Error(`${propKey} service is not defined`);
      },
    }
  ) as {
    AccountConsole: IAccountConsole;
    TeamConsole: ITeamConsole;
    AppManagement: IAppManagement;

  };
}
