//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FeatureFlagInteractions_ClientImpl(IonClientContext context) : IFeatureFlagInteractions
{
    
    private static readonly Lazy<MethodInfo> GetMyFeatureFlags_Ref = new(() =>
        typeof(IFeatureFlagInteractions).GetMethod(nameof(GetMyFeatureFlags), BindingFlags.Public | BindingFlags.Instance)!);


    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IonArray<FeatureFlagData>> GetMyFeatureFlags(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IFeatureFlagInteractions), GetMyFeatureFlags_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsyncWithArray<FeatureFlagData>(writer.Encode(), ct: ct);
    }

}

