//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UserInteraction_ClientImpl(IonClientContext context) : IUserInteraction
{
    
    private static readonly Lazy<MethodInfo> GetMe_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetMe), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> CreateSpace_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(CreateSpace), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> GetSpaces_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetSpaces), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> UpdateMe_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(UpdateMe), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> JoinToSpace_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(JoinToSpace), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> BroadcastPresence_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(BroadcastPresence), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> RemoveBroadcastPresence_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(RemoveBroadcastPresence), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> GetMyFeatures_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetMyFeatures), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> GetMyProfile_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetMyProfile), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> BeginUploadAvatar_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(BeginUploadAvatar), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> CompleteUploadAvatar_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(CompleteUploadAvatar), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> BeginUploadProfileHeader_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(BeginUploadProfileHeader), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> CompleteUploadProfileHeader_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(CompleteUploadProfileHeader), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> GetTodayStats_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetTodayStats), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> GetMyLevel_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetMyLevel), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> ClaimLevelCoin_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(ClaimLevelCoin), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> GetGlobalBadges_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetGlobalBadges), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> AckChannel_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(AckChannel), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> MuteTarget_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(MuteTarget), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> UnmuteTarget_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(UnmuteTarget), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> GetNotificationFeed_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(GetNotificationFeed), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> MarkNotificationRead_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(MarkNotificationRead), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> MarkAllNotificationsRead_Ref = new(() =>
        typeof(IUserInteraction).GetMethod(nameof(MarkAllNotificationsRead), BindingFlags.Public | BindingFlags.Instance)!);


    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<ArgonUser> GetMe(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetMe_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<ArgonUser>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<ICreateSpaceResult> CreateSpace(CreateServerRequest __request, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), CreateSpace_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 1;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<CreateServerRequest>.Write(writer, __request);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<ICreateSpaceResult>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IonArray<ArgonSpaceBase>> GetSpaces(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetSpaces_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsyncWithArray<ArgonSpaceBase>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<ArgonUser> UpdateMe(UserEditInput __request, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), UpdateMe_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 1;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<UserEditInput>.Write(writer, __request);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<ArgonUser>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IJoinToSpaceResult> JoinToSpace(InviteCode __invitecode, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), JoinToSpace_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 1;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<InviteCode>.Write(writer, __invitecode);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<IJoinToSpaceResult>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task BroadcastPresence(UserActivityPresence __presence, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), BroadcastPresence_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 1;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<UserActivityPresence>.Write(writer, __presence);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task RemoveBroadcastPresence(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), RemoveBroadcastPresence_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 0;

        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IonArray<FeatureFlag>> GetMyFeatures(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetMyFeatures_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsyncWithArray<FeatureFlag>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<ArgonUserProfile> GetMyProfile(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetMyProfile_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<ArgonUserProfile>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IUploadFileResult> BeginUploadAvatar(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), BeginUploadAvatar_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<IUploadFileResult>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task CompleteUploadAvatar(guid __blobid, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), CompleteUploadAvatar_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 1;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<guid>.Write(writer, __blobid);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IUploadFileResult> BeginUploadProfileHeader(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), BeginUploadProfileHeader_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<IUploadFileResult>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task CompleteUploadProfileHeader(guid __blobid, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), CompleteUploadProfileHeader_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 1;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<guid>.Write(writer, __blobid);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<TodayStats> GetTodayStats(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetTodayStats_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<TodayStats>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<MyLevelDetails> GetMyLevel(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetMyLevel_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<MyLevelDetails>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<bool> ClaimLevelCoin(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), ClaimLevelCoin_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<bool>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<GlobalBadges> GetGlobalBadges(CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetGlobalBadges_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 0;
    
        writer.WriteStartArray(argsSize);
        
        
        
        writer.WriteEndArray();
    
        return await req.CallAsync<GlobalBadges>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task AckChannel(guid __channelid, i8 __lastreadmessageid, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), AckChannel_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 2;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<guid>.Write(writer, __channelid);
        IonFormatterStorage<i8>.Write(writer, __lastreadmessageid);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task MuteTarget(guid __targetid, MuteTargetKind __targettype, MuteLevelType __mutelevel, bool __suppresseveryone, datetime? __expiresat, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), MuteTarget_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 5;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<guid>.Write(writer, __targetid);
        IonFormatterStorage<MuteTargetKind>.Write(writer, __targettype);
        IonFormatterStorage<MuteLevelType>.Write(writer, __mutelevel);
        IonFormatterStorage<bool>.Write(writer, __suppresseveryone);
        IonFormatterStorage<datetime>.WriteNullable(writer, __expiresat);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task UnmuteTarget(guid __targetid, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), UnmuteTarget_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 1;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<guid>.Write(writer, __targetid);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IonArray<SystemNotificationDto>> GetNotificationFeed(i4 __limit, datetime? __before, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), GetNotificationFeed_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 2;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<i4>.Write(writer, __limit);
        IonFormatterStorage<datetime>.WriteNullable(writer, __before);
        
        writer.WriteEndArray();
    
        return await req.CallAsyncWithArray<SystemNotificationDto>(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task MarkNotificationRead(guid __notificationid, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), MarkNotificationRead_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 1;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<guid>.Write(writer, __notificationid);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task MarkAllNotificationsRead(string? __type, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IUserInteraction), MarkAllNotificationsRead_Ref.Value);

        var writer = new CborWriter();
        
        const int argsSize = 1;

        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<string>.WriteNullable(writer, __type);
        
        writer.WriteEndArray();

        await req.CallAsync(writer.Encode(), ct: ct);
    }

}

