//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ConsoleContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
internal static class IonProjectFormatterStorageModuleInit
{
    [ModuleInitializer]
    internal static void Init()
    {
        
      IonFormatterStorage<SearchUserResult>.Value = new Ion_SearchUserResult_Formatter();
      IonFormatterStorage<UserCardDetails>.Value = new Ion_UserCardDetails_Formatter();
      IonFormatterStorage<UserAccountInfo>.Value = new Ion_UserAccountInfo_Formatter();
      IonFormatterStorage<InventoryItemInfo>.Value = new Ion_InventoryItemInfo_Formatter();
      IonFormatterStorage<BoxContentInfo>.Value = new Ion_BoxContentInfo_Formatter();
      IonFormatterStorage<MessageInfo>.Value = new Ion_MessageInfo_Formatter();
      IonFormatterStorage<DeviceHistoryInfo>.Value = new Ion_DeviceHistoryInfo_Formatter();
      IonFormatterStorage<RedeemedCouponInfo>.Value = new Ion_RedeemedCouponInfo_Formatter();
      IonFormatterStorage<UserSpaceInfo>.Value = new Ion_UserSpaceInfo_Formatter();
      IonFormatterStorage<UserLevelInfo>.Value = new Ion_UserLevelInfo_Formatter();
      IonFormatterStorage<UserStatsInfo>.Value = new Ion_UserStatsInfo_Formatter();
      IonFormatterStorage<UserTeamInfo>.Value = new Ion_UserTeamInfo_Formatter();
      IonFormatterStorage<AutoDeleteSettingsInfo>.Value = new Ion_AutoDeleteSettingsInfo_Formatter();
      IonFormatterStorage<PlatformStats>.Value = new Ion_PlatformStats_Formatter();
      IonFormatterStorage<ItemTemplateList>.Value = new Ion_ItemTemplateList_Formatter();
      IonFormatterStorage<ItemTemplateInfo>.Value = new Ion_ItemTemplateInfo_Formatter();
      IonFormatterStorage<CreateItemTemplateInput>.Value = new Ion_CreateItemTemplateInput_Formatter();
      IonFormatterStorage<CreateItemTemplateResult>.Value = new Ion_CreateItemTemplateResult_Formatter();
      IonFormatterStorage<DeleteItemResult>.Value = new Ion_DeleteItemResult_Formatter();
      IonFormatterStorage<CouponList>.Value = new Ion_CouponList_Formatter();
      IonFormatterStorage<CouponInfo>.Value = new Ion_CouponInfo_Formatter();
      IonFormatterStorage<CreateCouponInput>.Value = new Ion_CreateCouponInput_Formatter();
      IonFormatterStorage<CreateCouponResult>.Value = new Ion_CreateCouponResult_Formatter();
      IonFormatterStorage<UserActionResult>.Value = new Ion_UserActionResult_Formatter();
      IonFormatterStorage<DiagnosticsResult>.Value = new Ion_DiagnosticsResult_Formatter();
      IonFormatterStorage<RuntimeDiagnostics>.Value = new Ion_RuntimeDiagnostics_Formatter();
      IonFormatterStorage<DatabaseDiagnostics>.Value = new Ion_DatabaseDiagnostics_Formatter();
      IonFormatterStorage<KubernetesDiagnostics>.Value = new Ion_KubernetesDiagnostics_Formatter();
      IonFormatterStorage<NatsDiagnostics>.Value = new Ion_NatsDiagnostics_Formatter();
      IonFormatterStorage<RedisDiagnostics>.Value = new Ion_RedisDiagnostics_Formatter();
      IonFormatterStorage<OrleansDiagnostics>.Value = new Ion_OrleansDiagnostics_Formatter();
      IonFormatterStorage<SearchMatchKind>.Value = new Ion_SearchMatchKind_Formatter();
      IonFormatterStorage<ArgonAuthMode>.Value = new Ion_ArgonAuthMode_Formatter();
      IonFormatterStorage<OtpMethod>.Value = new Ion_OtpMethod_Formatter();
      IonFormatterStorage<DeviceTypeKind>.Value = new Ion_DeviceTypeKind_Formatter();
      IonFormatterStorage<ItemScenarioKind>.Value = new Ion_ItemScenarioKind_Formatter();
      IonExecutorMetadataStorage.AddExecutor<Ion_AdminConsole_ServiceExecutor>("IAdminConsole");
      IonExecutorMetadataStorage.AddClient<Ion_AdminConsole_ClientImpl>("IAdminConsole");

    }
}
