# NATS DC1 Node 2
server_name: nats-dc1-2
listen: 0.0.0.0:4222
http_port: 8222

jetstream {
  store_dir: /data/jetstream
  max_mem: 256MB
  max_file: 1GB
}

cluster {
  name: dc1
  listen: 0.0.0.0:6222
  routes: [
    nats-route://nats-dc1-1:6222
    nats-route://nats-dc1-3:6222
  ]
}

gateway {
  name: dc1
  listen: 0.0.0.0:7222
  gateways: [
    { name: dc2, urls: ["nats://nats-dc2-1:7222", "nats://nats-dc2-2:7222", "nats://nats-dc2-3:7222"] }
  ]
}
