//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FriendRequest(guid requestId, guid fromUser, guid toUser, datetime requestTime);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum FriendRequestStatus
{
    Pending = 0,
    Accepted = 1,
    Declined = 2,
    Cancelled = 3,
    Expired = 4,
    Blocked = 5,
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IFriendsInteraction : IIonService
{
}


