//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record UserBlock(guid userId, guid blockedId, datetime blockedAt);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FriendRequest(guid requesterId, guid targetId, datetime requestedAt);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record Friendship(guid userId, guid friendId, datetime friendAt);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record UserChat(guid peerId, bool isPinned, guid userId, string? lastMsg, datetime lastMessageAt, datetime? pinnedAt, i4 unreadCount);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum SendFriendStatus
{
    TargetNotFound = 0,
    CannotFriendYourself = 1,
    Blocked = 2,
    AlreadyFriends = 3,
    AutoAccepted = 4,
    AlreadySent = 5,
    SuccessSent = 6,
    FailedSent = 7,
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IFriendsInteraction : IIonService
{
    Task<IonArray<UserBlock>> GetBlockList(i4 limit, i4 offset, CancellationToken ct = default);
    Task<IonArray<FriendRequest>> GetMyFriendPendingList(i4 limit, i4 offset, CancellationToken ct = default);
    Task<IonArray<FriendRequest>> GetMyFriendOutgoingList(i4 limit, i4 offset, CancellationToken ct = default);
    Task<IonArray<Friendship>> GetMyFriendships(i4 limit, i4 offset, CancellationToken ct = default);
    Task<SendFriendStatus> SendFriendRequest(string username, CancellationToken ct = default);
    Task RemoveFriend(guid userId, CancellationToken ct = default);
    Task AcceptFriendRequest(guid fromUserId, CancellationToken ct = default);
    Task DeclineFriendRequest(guid fromUserId, CancellationToken ct = default);
    Task CancelFriendRequest(guid toUserId, CancellationToken ct = default);
    Task BlockUser(guid userId, CancellationToken ct = default);
    Task UnblockUser(guid userId, CancellationToken ct = default);
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IUserChatInteractions : IIonService
{
    Task<IonArray<UserChat>> GetRecentChats(i4 limit, i4 offset, CancellationToken ct = default);
    Task PinChat(guid peerId, CancellationToken ct = default);
    Task UnpinChat(guid peerId, CancellationToken ct = default);
    Task MarkChatRead(guid peerId, CancellationToken ct = default);
}


