//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IIdentityInteraction : IIonService
{
    [AllowAnonymous()]
    Task<IAuthorizeResult> Authorize(UserCredentialsInput data);
    [AllowAnonymous()]
    Task<IRegistrationResult> Registration(NewUserCredentialsInput data);
    [AllowAnonymous()]
    Task<bool> BeginResetPassword(string email);
    [AllowAnonymous()]
    Task<IAuthorizeResult> ResetPassword(string email, string otpCode, string newPassword);
    [AllowAnonymous()]
    Task<string> GetAuthorizationScenario();
}


