//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record LoginRequestTicket(string token, datetime expiresAt);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record LoginRequestPreview(string clientName, string? hostName, string ip, string region, datetime createdAt, datetime expiresAt);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum LoginRequestError : u4
{
    NONE = 0,
    NOT_FOUND = 1,
    EXPIRED = 2,
    ALREADY_USED = 3,
    DEVICE_MISMATCH = 4,
    RATE_LIMITED = 5,
    INTERNAL_ERROR = 6,
}

/// <summary>Open-enum helpers for <see cref="LoginRequestError"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_LoginRequestError_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this LoginRequestError value)
        => value == LoginRequestError.NONE || value == LoginRequestError.NOT_FOUND || value == LoginRequestError.EXPIRED || value == LoginRequestError.ALREADY_USED || value == LoginRequestError.DEVICE_MISMATCH || value == LoginRequestError.RATE_LIMITED || value == LoginRequestError.INTERNAL_ERROR;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this LoginRequestError value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum BadAuthKind : u4
{
    SESSION_EXPIRED = 0,
    REQUIRED_RELOGIN = 1,
    BAD_TOKEN = 2,
}

/// <summary>Open-enum helpers for <see cref="BadAuthKind"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_BadAuthKind_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this BadAuthKind value)
        => value == BadAuthKind.SESSION_EXPIRED || value == BadAuthKind.REQUIRED_RELOGIN || value == BadAuthKind.BAD_TOKEN;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this BadAuthKind value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IIdentityInteraction : IIonService
{
    [AllowAnonymous]
    Task<IAuthorizeResult> Authorize(UserCredentialsInput data, CancellationToken ct = default);
    [AllowAnonymous]
    Task<IRegistrationResult> Registration(NewUserCredentialsInput data, CancellationToken ct = default);
    [AllowAnonymous]
    Task<bool> BeginResetPassword(string email, CancellationToken ct = default);
    [AllowAnonymous]
    Task<IAuthorizeResult> ResetPassword(string email, string otpCode, string newPassword, CancellationToken ct = default);
    [AllowAnonymous]
    Task<string> GetAuthorizationScenario(CancellationToken ct = default);
    [AllowAnonymous]
    Task<string> GetAuthorizationScenarioFor(UserLoginInput data, CancellationToken ct = default);
    [AllowAnonymous]
    [DoNotRequireSessionContext]
    Task<IMyAuthStatus> GetMyAuthorization(string token, string? refreshToken, CancellationToken ct = default);
    [AllowAnonymous]
    Task<ICreateLoginRequestResult> CreateLoginRequest(CancellationToken ct = default);
    [AllowAnonymous]
    Task<ILoginPollResult> PollLoginRequest(string token, CancellationToken ct = default);
    Task<ILoginRequestPreviewResult> PreviewLoginRequest(string token, CancellationToken ct = default);
    Task<IApproveLoginRequestResult> ApproveLoginRequest(string token, CancellationToken ct = default);
    Task<IRejectLoginRequestResult> RejectLoginRequest(string token, CancellationToken ct = default);
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ICreateLoginRequestResult : IIonUnion<ICreateLoginRequestResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessCreateLoginRequest => this is SuccessCreateLoginRequest;

    internal bool IsFailedCreateLoginRequest => this is FailedCreateLoginRequest;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessCreateLoginRequest(LoginRequestTicket ticket) : ICreateLoginRequestResult
{
    public string UnionKey => nameof(SuccessCreateLoginRequest);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedCreateLoginRequest(LoginRequestError error) : ICreateLoginRequestResult
{
    public string UnionKey => nameof(FailedCreateLoginRequest);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ICreateLoginRequestResult_Formatter : IonFormatter<ICreateLoginRequestResult>
{
    public ICreateLoginRequestResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("ICreateLoginRequestResult", 2u);
        ICreateLoginRequestResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessCreateLoginRequest>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedCreateLoginRequest>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("ICreateLoginRequestResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, ICreateLoginRequestResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessCreateLoginRequest n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessCreateLoginRequest>.Write(writer, n_0);
        }

        else if (value is FailedCreateLoginRequest n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedCreateLoginRequest>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'ICreateLoginRequestResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessCreateLoginRequest_Formatter : IonFormatter<SuccessCreateLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessCreateLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "SuccessCreateLoginRequest");
        var __ticket = IonFormatterStorage<LoginRequestTicket>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__ticket);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessCreateLoginRequest value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LoginRequestTicket>.Write(writer, value.ticket);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedCreateLoginRequest_Formatter : IonFormatter<FailedCreateLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedCreateLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedCreateLoginRequest");
        var __error = IonFormatterStorage<LoginRequestError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedCreateLoginRequest value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LoginRequestError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ILoginPollResult : IIonUnion<ILoginPollResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsPendingLoginRequest => this is PendingLoginRequest;

    internal bool IsApprovedLoginRequest => this is ApprovedLoginRequest;

    internal bool IsRejectedLoginRequest => this is RejectedLoginRequest;

    internal bool IsFailedLoginPoll => this is FailedLoginPoll;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record PendingLoginRequest(datetime expiresAt) : ILoginPollResult
{
    public string UnionKey => nameof(PendingLoginRequest);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ApprovedLoginRequest(string token, string? refreshToken) : ILoginPollResult
{
    public string UnionKey => nameof(ApprovedLoginRequest);
    public uint UnionIndex => 1;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record RejectedLoginRequest() : ILoginPollResult
{
    public string UnionKey => nameof(RejectedLoginRequest);
    public uint UnionIndex => 2;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedLoginPoll(LoginRequestError error) : ILoginPollResult
{
    public string UnionKey => nameof(FailedLoginPoll);
    public uint UnionIndex => 3;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ILoginPollResult_Formatter : IonFormatter<ILoginPollResult>
{
    public ILoginPollResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("ILoginPollResult", 4u);
        ILoginPollResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<PendingLoginRequest>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<ApprovedLoginRequest>.Read(reader);

        else if (unionIndex == 2)
            result = IonFormatterStorage<RejectedLoginRequest>.Read(reader);

        else if (unionIndex == 3)
            result = IonFormatterStorage<FailedLoginPoll>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("ILoginPollResult", unionIndex, 4u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, ILoginPollResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is PendingLoginRequest n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<PendingLoginRequest>.Write(writer, n_0);
        }

        else if (value is ApprovedLoginRequest n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<ApprovedLoginRequest>.Write(writer, n_1);
        }

        else if (value is RejectedLoginRequest n_2)
        {
            if (n_2.UnionIndex != 2)
                throw new InvalidOperationException();
            IonFormatterStorage<RejectedLoginRequest>.Write(writer, n_2);
        }

        else if (value is FailedLoginPoll n_3)
        {
            if (n_3.UnionIndex != 3)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedLoginPoll>.Write(writer, n_3);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'ILoginPollResult' has no case {value.UnionIndex}; this revision declares 4 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_PendingLoginRequest_Formatter : IonFormatter<PendingLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public PendingLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "PendingLoginRequest");
        var __expiresat = IonFormatterStorage<datetime>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__expiresat);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, PendingLoginRequest value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<datetime>.Write(writer, value.expiresAt);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ApprovedLoginRequest_Formatter : IonFormatter<ApprovedLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ApprovedLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "ApprovedLoginRequest");
        var __token = IonFormatterStorage<string>.Read(reader);
        var __refreshtoken = reader.ReadNullable<string>();
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__token, __refreshtoken);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ApprovedLoginRequest value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<string>.Write(writer, value.token);
        IonFormatterStorage<string>.WriteNullable(writer, value.refreshToken);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_RejectedLoginRequest_Formatter : IonFormatter<RejectedLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public RejectedLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(0, "RejectedLoginRequest");
        
        reader.ReadEndArrayAndSkip(arraySize - 0);
        return new();
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, RejectedLoginRequest value)
    {
        writer.WriteStartArray(0);
        
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedLoginPoll_Formatter : IonFormatter<FailedLoginPoll>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedLoginPoll Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedLoginPoll");
        var __error = IonFormatterStorage<LoginRequestError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedLoginPoll value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LoginRequestError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ILoginRequestPreviewResult : IIonUnion<ILoginRequestPreviewResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessLoginRequestPreview => this is SuccessLoginRequestPreview;

    internal bool IsFailedLoginRequestPreview => this is FailedLoginRequestPreview;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessLoginRequestPreview(LoginRequestPreview preview) : ILoginRequestPreviewResult
{
    public string UnionKey => nameof(SuccessLoginRequestPreview);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedLoginRequestPreview(LoginRequestError error) : ILoginRequestPreviewResult
{
    public string UnionKey => nameof(FailedLoginRequestPreview);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ILoginRequestPreviewResult_Formatter : IonFormatter<ILoginRequestPreviewResult>
{
    public ILoginRequestPreviewResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("ILoginRequestPreviewResult", 2u);
        ILoginRequestPreviewResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessLoginRequestPreview>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedLoginRequestPreview>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("ILoginRequestPreviewResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, ILoginRequestPreviewResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessLoginRequestPreview n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessLoginRequestPreview>.Write(writer, n_0);
        }

        else if (value is FailedLoginRequestPreview n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedLoginRequestPreview>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'ILoginRequestPreviewResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessLoginRequestPreview_Formatter : IonFormatter<SuccessLoginRequestPreview>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessLoginRequestPreview Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "SuccessLoginRequestPreview");
        var __preview = IonFormatterStorage<LoginRequestPreview>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__preview);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessLoginRequestPreview value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LoginRequestPreview>.Write(writer, value.preview);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedLoginRequestPreview_Formatter : IonFormatter<FailedLoginRequestPreview>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedLoginRequestPreview Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedLoginRequestPreview");
        var __error = IonFormatterStorage<LoginRequestError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedLoginRequestPreview value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LoginRequestError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IApproveLoginRequestResult : IIonUnion<IApproveLoginRequestResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessApproveLoginRequest => this is SuccessApproveLoginRequest;

    internal bool IsFailedApproveLoginRequest => this is FailedApproveLoginRequest;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessApproveLoginRequest() : IApproveLoginRequestResult
{
    public string UnionKey => nameof(SuccessApproveLoginRequest);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedApproveLoginRequest(LoginRequestError error) : IApproveLoginRequestResult
{
    public string UnionKey => nameof(FailedApproveLoginRequest);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IApproveLoginRequestResult_Formatter : IonFormatter<IApproveLoginRequestResult>
{
    public IApproveLoginRequestResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IApproveLoginRequestResult", 2u);
        IApproveLoginRequestResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessApproveLoginRequest>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedApproveLoginRequest>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IApproveLoginRequestResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IApproveLoginRequestResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessApproveLoginRequest n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessApproveLoginRequest>.Write(writer, n_0);
        }

        else if (value is FailedApproveLoginRequest n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedApproveLoginRequest>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IApproveLoginRequestResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessApproveLoginRequest_Formatter : IonFormatter<SuccessApproveLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessApproveLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(0, "SuccessApproveLoginRequest");
        
        reader.ReadEndArrayAndSkip(arraySize - 0);
        return new();
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessApproveLoginRequest value)
    {
        writer.WriteStartArray(0);
        
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedApproveLoginRequest_Formatter : IonFormatter<FailedApproveLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedApproveLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedApproveLoginRequest");
        var __error = IonFormatterStorage<LoginRequestError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedApproveLoginRequest value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LoginRequestError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IRejectLoginRequestResult : IIonUnion<IRejectLoginRequestResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessRejectLoginRequest => this is SuccessRejectLoginRequest;

    internal bool IsFailedRejectLoginRequest => this is FailedRejectLoginRequest;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessRejectLoginRequest() : IRejectLoginRequestResult
{
    public string UnionKey => nameof(SuccessRejectLoginRequest);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedRejectLoginRequest(LoginRequestError error) : IRejectLoginRequestResult
{
    public string UnionKey => nameof(FailedRejectLoginRequest);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IRejectLoginRequestResult_Formatter : IonFormatter<IRejectLoginRequestResult>
{
    public IRejectLoginRequestResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IRejectLoginRequestResult", 2u);
        IRejectLoginRequestResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessRejectLoginRequest>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedRejectLoginRequest>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IRejectLoginRequestResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IRejectLoginRequestResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessRejectLoginRequest n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessRejectLoginRequest>.Write(writer, n_0);
        }

        else if (value is FailedRejectLoginRequest n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedRejectLoginRequest>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IRejectLoginRequestResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessRejectLoginRequest_Formatter : IonFormatter<SuccessRejectLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessRejectLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(0, "SuccessRejectLoginRequest");
        
        reader.ReadEndArrayAndSkip(arraySize - 0);
        return new();
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessRejectLoginRequest value)
    {
        writer.WriteStartArray(0);
        
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedRejectLoginRequest_Formatter : IonFormatter<FailedRejectLoginRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedRejectLoginRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedRejectLoginRequest");
        var __error = IonFormatterStorage<LoginRequestError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedRejectLoginRequest value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LoginRequestError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IMyAuthStatus : IIonUnion<IMyAuthStatus>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsGoodAuthStatus => this is GoodAuthStatus;

    internal bool IsBadAuthStatus => this is BadAuthStatus;

    internal bool IsLockedAuthStatus => this is LockedAuthStatus;

    internal bool IsCertificateErrorAuthStatus => this is CertificateErrorAuthStatus;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record GoodAuthStatus(string token) : IMyAuthStatus
{
    public string UnionKey => nameof(GoodAuthStatus);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record BadAuthStatus(BadAuthKind error) : IMyAuthStatus
{
    public string UnionKey => nameof(BadAuthStatus);
    public uint UnionIndex => 1;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record LockedAuthStatus(LockdownReason? lockdownReason, datetime? lockDownExpiration, bool isAppealable, LockdownSeverity severity) : IMyAuthStatus
{
    public string UnionKey => nameof(LockedAuthStatus);
    public uint UnionIndex => 2;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record CertificateErrorAuthStatus(string message) : IMyAuthStatus
{
    public string UnionKey => nameof(CertificateErrorAuthStatus);
    public uint UnionIndex => 3;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IMyAuthStatus_Formatter : IonFormatter<IMyAuthStatus>
{
    public IMyAuthStatus Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IMyAuthStatus", 4u);
        IMyAuthStatus result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<GoodAuthStatus>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<BadAuthStatus>.Read(reader);

        else if (unionIndex == 2)
            result = IonFormatterStorage<LockedAuthStatus>.Read(reader);

        else if (unionIndex == 3)
            result = IonFormatterStorage<CertificateErrorAuthStatus>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IMyAuthStatus", unionIndex, 4u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IMyAuthStatus value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is GoodAuthStatus n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<GoodAuthStatus>.Write(writer, n_0);
        }

        else if (value is BadAuthStatus n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<BadAuthStatus>.Write(writer, n_1);
        }

        else if (value is LockedAuthStatus n_2)
        {
            if (n_2.UnionIndex != 2)
                throw new InvalidOperationException();
            IonFormatterStorage<LockedAuthStatus>.Write(writer, n_2);
        }

        else if (value is CertificateErrorAuthStatus n_3)
        {
            if (n_3.UnionIndex != 3)
                throw new InvalidOperationException();
            IonFormatterStorage<CertificateErrorAuthStatus>.Write(writer, n_3);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IMyAuthStatus' has no case {value.UnionIndex}; this revision declares 4 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_GoodAuthStatus_Formatter : IonFormatter<GoodAuthStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public GoodAuthStatus Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "GoodAuthStatus");
        var __token = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__token);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, GoodAuthStatus value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<string>.Write(writer, value.token);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_BadAuthStatus_Formatter : IonFormatter<BadAuthStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public BadAuthStatus Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "BadAuthStatus");
        var __error = IonFormatterStorage<BadAuthKind>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, BadAuthStatus value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<BadAuthKind>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LockedAuthStatus_Formatter : IonFormatter<LockedAuthStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LockedAuthStatus Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(4, "LockedAuthStatus");
        var __lockdownreason = reader.ReadNullable<LockdownReason>();
        var __lockdownexpiration = reader.ReadNullable<datetime>();
        var __isappealable = IonFormatterStorage<bool>.Read(reader);
        var __severity = IonFormatterStorage<LockdownSeverity>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 4);
        return new(__lockdownreason, __lockdownexpiration, __isappealable, __severity);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LockedAuthStatus value)
    {
        writer.WriteStartArray(4);
        IonFormatterStorage<LockdownReason>.WriteNullable(writer, value.lockdownReason);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.lockDownExpiration);
        IonFormatterStorage<bool>.Write(writer, value.isAppealable);
        IonFormatterStorage<LockdownSeverity>.Write(writer, value.severity);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CertificateErrorAuthStatus_Formatter : IonFormatter<CertificateErrorAuthStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CertificateErrorAuthStatus Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "CertificateErrorAuthStatus");
        var __message = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__message);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CertificateErrorAuthStatus value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<string>.Write(writer, value.message);
        writer.WriteEndArray();
    }
}


