//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LoginRequestTicket_Formatter : IonFormatter<LoginRequestTicket>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LoginRequestTicket Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "LoginRequestTicket");
        var __token = IonFormatterStorage<string>.Read(reader);
        var __expiresat = IonFormatterStorage<datetime>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__token, __expiresat);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LoginRequestTicket value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<string>.Write(writer, value.token);
        IonFormatterStorage<datetime>.Write(writer, value.expiresAt);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LoginRequestPreview_Formatter : IonFormatter<LoginRequestPreview>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LoginRequestPreview Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(6, "LoginRequestPreview");
        var __clientname = IonFormatterStorage<string>.Read(reader);
        var __hostname = reader.ReadNullable<string>();
        var __ip = IonFormatterStorage<string>.Read(reader);
        var __region = IonFormatterStorage<string>.Read(reader);
        var __createdat = IonFormatterStorage<datetime>.Read(reader);
        var __expiresat = IonFormatterStorage<datetime>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 6);
        return new(__clientname, __hostname, __ip, __region, __createdat, __expiresat);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LoginRequestPreview value)
    {
        writer.WriteStartArray(6);
        IonFormatterStorage<string>.Write(writer, value.clientName);
        IonFormatterStorage<string>.WriteNullable(writer, value.hostName);
        IonFormatterStorage<string>.Write(writer, value.ip);
        IonFormatterStorage<string>.Write(writer, value.region);
        IonFormatterStorage<datetime>.Write(writer, value.createdAt);
        IonFormatterStorage<datetime>.Write(writer, value.expiresAt);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LoginRequestError_Formatter : IonFormatter<LoginRequestError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LoginRequestError Read(CborReader reader)
    {
         return (LoginRequestError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LoginRequestError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_BadAuthKind_Formatter : IonFormatter<BadAuthKind>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public BadAuthKind Read(CborReader reader)
    {
         return (BadAuthKind)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, BadAuthKind value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

