//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record LinkPreview(string url, string? title, string? description, string? siteName, string? imageUrl, string? canonicalUrl);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum LinkPreviewError
{
    NONE = 0,
    INVALID_URL = 1,
    NO_PREVIEW = 2,
    UNAVAILABLE = 3,
    RATE_LIMITED = 4,
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ILinkPreviewInteraction : IIonService
{
    Task<ILinkPreviewResult> GetLinkPreview(string url, CancellationToken ct = default);
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ILinkPreviewResult : IIonUnion<ILinkPreviewResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsLinkPreviewReady => this is LinkPreviewReady;

    internal bool IsLinkPreviewFailed => this is LinkPreviewFailed;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record LinkPreviewReady(LinkPreview preview) : ILinkPreviewResult
{
    public string UnionKey => nameof(LinkPreviewReady);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record LinkPreviewFailed(LinkPreviewError error) : ILinkPreviewResult
{
    public string UnionKey => nameof(LinkPreviewFailed);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ILinkPreviewResult_Formatter : IonFormatter<ILinkPreviewResult>
{
    public ILinkPreviewResult Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
        var unionIndex = reader.ReadUInt32();
        ILinkPreviewResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<LinkPreviewReady>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<LinkPreviewFailed>.Read(reader);

        else
            throw new InvalidOperationException();
        reader.ReadEndArray();
        return result;
    }

    public void Write(CborWriter writer, ILinkPreviewResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is LinkPreviewReady n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<LinkPreviewReady>.Write(writer, n_0);
        }

        else if (value is LinkPreviewFailed n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<LinkPreviewFailed>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException();
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LinkPreviewReady_Formatter : IonFormatter<LinkPreviewReady>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LinkPreviewReady Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __preview = IonFormatterStorage<LinkPreview>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__preview);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LinkPreviewReady value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LinkPreview>.Write(writer, value.preview);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LinkPreviewFailed_Formatter : IonFormatter<LinkPreviewFailed>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LinkPreviewFailed Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __error = IonFormatterStorage<LinkPreviewError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LinkPreviewFailed value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<LinkPreviewError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}


