//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LinkPreview_Formatter : IonFormatter<LinkPreview>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LinkPreview Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __url = IonFormatterStorage<string>.Read(reader);
        var __title = reader.ReadNullable<string>();
        var __description = reader.ReadNullable<string>();
        var __sitename = reader.ReadNullable<string>();
        var __imageurl = reader.ReadNullable<string>();
        var __canonicalurl = reader.ReadNullable<string>();
        reader.ReadEndArrayAndSkip(arraySize - 6);
        return new(__url, __title, __description, __sitename, __imageurl, __canonicalurl);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LinkPreview value)
    {
        writer.WriteStartArray(6);
        IonFormatterStorage<string>.Write(writer, value.url);
        IonFormatterStorage<string>.WriteNullable(writer, value.title);
        IonFormatterStorage<string>.WriteNullable(writer, value.description);
        IonFormatterStorage<string>.WriteNullable(writer, value.siteName);
        IonFormatterStorage<string>.WriteNullable(writer, value.imageUrl);
        IonFormatterStorage<string>.WriteNullable(writer, value.canonicalUrl);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LinkPreviewError_Formatter : IonFormatter<LinkPreviewError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LinkPreviewError Read(CborReader reader)
    {
         return (LinkPreviewError)(IonFormatterStorage<u2>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LinkPreviewError value)
    {
        var casted = (u2)value;
        IonFormatterStorage<u2>.Write(writer, casted);
    }
}

