//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReportTarget_Formatter : IonFormatter<ReportTarget>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReportTarget Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __kind = IonFormatterStorage<ReportTargetKind>.Read(reader);
        var __targetid = IonFormatterStorage<guid>.Read(reader);
        var __channelid = reader.ReadNullable<guid>();
        var __messageid = reader.ReadNullable<u8>();
        reader.ReadEndArrayAndSkip(arraySize - 4);
        return new(__kind, __targetid, __channelid, __messageid);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReportTarget value)
    {
        writer.WriteStartArray(4);
        IonFormatterStorage<ReportTargetKind>.Write(writer, value.kind);
        IonFormatterStorage<guid>.Write(writer, value.targetId);
        IonFormatterStorage<guid>.WriteNullable(writer, value.channelId);
        IonFormatterStorage<u8>.WriteNullable(writer, value.messageId);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CreateReportInput_Formatter : IonFormatter<CreateReportInput>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CreateReportInput Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __target = IonFormatterStorage<ReportTarget>.Read(reader);
        var __category = IonFormatterStorage<ReportCategory>.Read(reader);
        var __reason = IonFormatterStorage<ReportReason>.Read(reader);
        var __additionalinfo = reader.ReadNullable<string>();
        var __referencereportid = reader.ReadNullable<guid>();
        reader.ReadEndArrayAndSkip(arraySize - 5);
        return new(__target, __category, __reason, __additionalinfo, __referencereportid);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CreateReportInput value)
    {
        writer.WriteStartArray(5);
        IonFormatterStorage<ReportTarget>.Write(writer, value.target);
        IonFormatterStorage<ReportCategory>.Write(writer, value.category);
        IonFormatterStorage<ReportReason>.Write(writer, value.reason);
        IonFormatterStorage<string>.WriteNullable(writer, value.additionalInfo);
        IonFormatterStorage<guid>.WriteNullable(writer, value.referenceReportId);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReportInfo_Formatter : IonFormatter<ReportInfo>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReportInfo Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __reportid = IonFormatterStorage<guid>.Read(reader);
        var __reporterid = IonFormatterStorage<guid>.Read(reader);
        var __target = IonFormatterStorage<ReportTarget>.Read(reader);
        var __category = IonFormatterStorage<ReportCategory>.Read(reader);
        var __reason = IonFormatterStorage<ReportReason>.Read(reader);
        var __additionalinfo = reader.ReadNullable<string>();
        var __status = IonFormatterStorage<ReportStatus>.Read(reader);
        var __referencereportid = reader.ReadNullable<guid>();
        var __createdat = IonFormatterStorage<datetime>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 9);
        return new(__reportid, __reporterid, __target, __category, __reason, __additionalinfo, __status, __referencereportid, __createdat);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReportInfo value)
    {
        writer.WriteStartArray(9);
        IonFormatterStorage<guid>.Write(writer, value.reportId);
        IonFormatterStorage<guid>.Write(writer, value.reporterId);
        IonFormatterStorage<ReportTarget>.Write(writer, value.target);
        IonFormatterStorage<ReportCategory>.Write(writer, value.category);
        IonFormatterStorage<ReportReason>.Write(writer, value.reason);
        IonFormatterStorage<string>.WriteNullable(writer, value.additionalInfo);
        IonFormatterStorage<ReportStatus>.Write(writer, value.status);
        IonFormatterStorage<guid>.WriteNullable(writer, value.referenceReportId);
        IonFormatterStorage<datetime>.Write(writer, value.createdAt);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UserTrustInfo_Formatter : IonFormatter<UserTrustInfo>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UserTrustInfo Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __userid = IonFormatterStorage<guid>.Read(reader);
        var __trustscore = IonFormatterStorage<i4>.Read(reader);
        var __totalreportsreceived = IonFormatterStorage<i4>.Read(reader);
        var __confirmedreportsreceived = IonFormatterStorage<i4>.Read(reader);
        var __totalreportsfiled = IonFormatterStorage<i4>.Read(reader);
        var __falsereportsfiled = IonFormatterStorage<i4>.Read(reader);
        var __lastupdated = IonFormatterStorage<datetime>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 7);
        return new(__userid, __trustscore, __totalreportsreceived, __confirmedreportsreceived, __totalreportsfiled, __falsereportsfiled, __lastupdated);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UserTrustInfo value)
    {
        writer.WriteStartArray(7);
        IonFormatterStorage<guid>.Write(writer, value.userId);
        IonFormatterStorage<i4>.Write(writer, value.trustScore);
        IonFormatterStorage<i4>.Write(writer, value.totalReportsReceived);
        IonFormatterStorage<i4>.Write(writer, value.confirmedReportsReceived);
        IonFormatterStorage<i4>.Write(writer, value.totalReportsFiled);
        IonFormatterStorage<i4>.Write(writer, value.falseReportsFiled);
        IonFormatterStorage<datetime>.Write(writer, value.lastUpdated);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReportTargetKind_Formatter : IonFormatter<ReportTargetKind>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReportTargetKind Read(CborReader reader)
    {
         return (ReportTargetKind)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReportTargetKind value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReportCategory_Formatter : IonFormatter<ReportCategory>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReportCategory Read(CborReader reader)
    {
         return (ReportCategory)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReportCategory value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReportReason_Formatter : IonFormatter<ReportReason>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReportReason Read(CborReader reader)
    {
         return (ReportReason)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReportReason value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReportStatus_Formatter : IonFormatter<ReportStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReportStatus Read(CborReader reader)
    {
         return (ReportStatus)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReportStatus value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SubmitReportError_Formatter : IonFormatter<SubmitReportError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SubmitReportError Read(CborReader reader)
    {
         return (SubmitReportError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SubmitReportError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

