//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ArgonIonTicket(guid userId, string ip, string ray, string clientName, string hostName, string appId, guid sessionId, string machineId, string region);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum ArgonAuthMode
{
    EmailPassword = 0,
    EmailOtp = 1,
    EmailPasswordOtp = 2,
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum OtpMethod
{
    Email = 0,
    Phone = 1,
    Totp = 2,
}


[AttributeUsage(AttributeTargets.All)]
public sealed class AllowAnonymousAttribute() : System.Attribute
{

}

[AttributeUsage(AttributeTargets.All)]
public sealed class MachineIdOptionalAttribute() : System.Attribute
{

}

[AttributeUsage(AttributeTargets.All)]
public sealed class DoNotRequireSessionContextAttribute() : System.Attribute
{

}

