//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UltimaPricing_Formatter : IonFormatter<UltimaPricing>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UltimaPricing Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __subscriptionmonthly = IonFormatterStorage<ProductPrice>.Read(reader);
        var __subscriptionannual = IonFormatterStorage<ProductPrice>.Read(reader);
        var __boostpack1 = IonFormatterStorage<ProductPrice>.Read(reader);
        var __boostpack3 = IonFormatterStorage<ProductPrice>.Read(reader);
        var __boostpack5 = IonFormatterStorage<ProductPrice>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 5);
        return new(__subscriptionmonthly, __subscriptionannual, __boostpack1, __boostpack3, __boostpack5);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UltimaPricing value)
    {
        writer.WriteStartArray(5);
        IonFormatterStorage<ProductPrice>.Write(writer, value.subscriptionMonthly);
        IonFormatterStorage<ProductPrice>.Write(writer, value.subscriptionAnnual);
        IonFormatterStorage<ProductPrice>.Write(writer, value.boostPack1);
        IonFormatterStorage<ProductPrice>.Write(writer, value.boostPack3);
        IonFormatterStorage<ProductPrice>.Write(writer, value.boostPack5);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ProductPrice_Formatter : IonFormatter<ProductPrice>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ProductPrice Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __amount = IonFormatterStorage<string>.Read(reader);
        var __amountwithoutdiscount = reader.ReadNullable<string>();
        var __currency = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__amount, __amountwithoutdiscount, __currency);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ProductPrice value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<string>.Write(writer, value.amount);
        IonFormatterStorage<string>.WriteNullable(writer, value.amountWithoutDiscount);
        IonFormatterStorage<string>.Write(writer, value.currency);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UltimaSubscriptionInfo_Formatter : IonFormatter<UltimaSubscriptionInfo>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UltimaSubscriptionInfo Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __subscriptionid = IonFormatterStorage<guid>.Read(reader);
        var __tier = IonFormatterStorage<UltimaPlan>.Read(reader);
        var __status = IonFormatterStorage<UltimaSubscriptionStatus>.Read(reader);
        var __startsat = IonFormatterStorage<datetime>.Read(reader);
        var __expiresat = IonFormatterStorage<datetime>.Read(reader);
        var __autorenew = IonFormatterStorage<bool>.Read(reader);
        var __totalboostslots = IonFormatterStorage<i4>.Read(reader);
        var __usedboostslots = IonFormatterStorage<i4>.Read(reader);
        var __paymentaccount = reader.ReadNullable<PaymentAccountInfo>();
        reader.ReadEndArrayAndSkip(arraySize - 9);
        return new(__subscriptionid, __tier, __status, __startsat, __expiresat, __autorenew, __totalboostslots, __usedboostslots, __paymentaccount);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UltimaSubscriptionInfo value)
    {
        writer.WriteStartArray(9);
        IonFormatterStorage<guid>.Write(writer, value.subscriptionId);
        IonFormatterStorage<UltimaPlan>.Write(writer, value.tier);
        IonFormatterStorage<UltimaSubscriptionStatus>.Write(writer, value.status);
        IonFormatterStorage<datetime>.Write(writer, value.startsAt);
        IonFormatterStorage<datetime>.Write(writer, value.expiresAt);
        IonFormatterStorage<bool>.Write(writer, value.autoRenew);
        IonFormatterStorage<i4>.Write(writer, value.totalBoostSlots);
        IonFormatterStorage<i4>.Write(writer, value.usedBoostSlots);
        IonFormatterStorage<PaymentAccountInfo>.WriteNullable(writer, value.paymentAccount);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_PaymentAccountInfo_Formatter : IonFormatter<PaymentAccountInfo>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public PaymentAccountInfo Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __cardlastfour = reader.ReadNullable<string>();
        var __cardtype = reader.ReadNullable<string>();
        var __expirymonth = reader.ReadNullable<string>();
        var __expiryyear = reader.ReadNullable<string>();
        reader.ReadEndArrayAndSkip(arraySize - 4);
        return new(__cardlastfour, __cardtype, __expirymonth, __expiryyear);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, PaymentAccountInfo value)
    {
        writer.WriteStartArray(4);
        IonFormatterStorage<string>.WriteNullable(writer, value.cardLastFour);
        IonFormatterStorage<string>.WriteNullable(writer, value.cardType);
        IonFormatterStorage<string>.WriteNullable(writer, value.expiryMonth);
        IonFormatterStorage<string>.WriteNullable(writer, value.expiryYear);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UltimaTransaction_Formatter : IonFormatter<UltimaTransaction>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UltimaTransaction Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __paymentid = IonFormatterStorage<string>.Read(reader);
        var __date = IonFormatterStorage<datetime>.Read(reader);
        var __amount = reader.ReadNullable<string>();
        var __currency = reader.ReadNullable<string>();
        var __planexternalid = reader.ReadNullable<string>();
        var __boostpacktype = reader.ReadNullable<string>();
        var __boostcount = reader.ReadNullable<i4>();
        var __recipientid = reader.ReadNullable<guid>();
        var __transactiontype = reader.ReadNullable<string>();
        reader.ReadEndArrayAndSkip(arraySize - 9);
        return new(__paymentid, __date, __amount, __currency, __planexternalid, __boostpacktype, __boostcount, __recipientid, __transactiontype);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UltimaTransaction value)
    {
        writer.WriteStartArray(9);
        IonFormatterStorage<string>.Write(writer, value.paymentId);
        IonFormatterStorage<datetime>.Write(writer, value.date);
        IonFormatterStorage<string>.WriteNullable(writer, value.amount);
        IonFormatterStorage<string>.WriteNullable(writer, value.currency);
        IonFormatterStorage<string>.WriteNullable(writer, value.planExternalId);
        IonFormatterStorage<string>.WriteNullable(writer, value.boostPackType);
        IonFormatterStorage<i4>.WriteNullable(writer, value.boostCount);
        IonFormatterStorage<guid>.WriteNullable(writer, value.recipientId);
        IonFormatterStorage<string>.WriteNullable(writer, value.transactionType);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UltimaBoost_Formatter : IonFormatter<UltimaBoost>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UltimaBoost Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __boostid = IonFormatterStorage<guid>.Read(reader);
        var __spaceid = reader.ReadNullable<guid>();
        var __spacename = reader.ReadNullable<string>();
        var __appliedat = reader.ReadNullable<datetime>();
        var __transfercooldownuntil = reader.ReadNullable<datetime>();
        var __source = IonFormatterStorage<BoostSource>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 6);
        return new(__boostid, __spaceid, __spacename, __appliedat, __transfercooldownuntil, __source);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UltimaBoost value)
    {
        writer.WriteStartArray(6);
        IonFormatterStorage<guid>.Write(writer, value.boostId);
        IonFormatterStorage<guid>.WriteNullable(writer, value.spaceId);
        IonFormatterStorage<string>.WriteNullable(writer, value.spaceName);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.appliedAt);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.transferCooldownUntil);
        IonFormatterStorage<BoostSource>.Write(writer, value.source);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SpaceBoostStatus_Formatter : IonFormatter<SpaceBoostStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SpaceBoostStatus Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __boostcount = IonFormatterStorage<i4>.Read(reader);
        var __boostlevel = IonFormatterStorage<i4>.Read(reader);
        var __boosters = IonFormatterStorage<SpaceBooster>.ReadArray(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__boostcount, __boostlevel, __boosters);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SpaceBoostStatus value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.boostCount);
        IonFormatterStorage<i4>.Write(writer, value.boostLevel);
        IonFormatterStorage<SpaceBooster>.WriteArray(writer, value.boosters);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SpaceBooster_Formatter : IonFormatter<SpaceBooster>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SpaceBooster Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __userid = IonFormatterStorage<guid>.Read(reader);
        var __username = IonFormatterStorage<string>.Read(reader);
        var __boostcount = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__userid, __username, __boostcount);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SpaceBooster value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<guid>.Write(writer, value.userId);
        IonFormatterStorage<string>.Write(writer, value.username);
        IonFormatterStorage<i4>.Write(writer, value.boostCount);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UltimaPlan_Formatter : IonFormatter<UltimaPlan>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UltimaPlan Read(CborReader reader)
    {
         return (UltimaPlan)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UltimaPlan value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UltimaSubscriptionStatus_Formatter : IonFormatter<UltimaSubscriptionStatus>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UltimaSubscriptionStatus Read(CborReader reader)
    {
         return (UltimaSubscriptionStatus)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UltimaSubscriptionStatus value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_BoostPackType_Formatter : IonFormatter<BoostPackType>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public BoostPackType Read(CborReader reader)
    {
         return (BoostPackType)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, BoostPackType value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_BoostSource_Formatter : IonFormatter<BoostSource>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public BoostSource Read(CborReader reader)
    {
         return (BoostSource)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, BoostSource value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CheckoutError_Formatter : IonFormatter<CheckoutError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CheckoutError Read(CborReader reader)
    {
         return (CheckoutError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CheckoutError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ApplyBoostError_Formatter : IonFormatter<ApplyBoostError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ApplyBoostError Read(CborReader reader)
    {
         return (ApplyBoostError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ApplyBoostError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_TransferBoostError_Formatter : IonFormatter<TransferBoostError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public TransferBoostError Read(CborReader reader)
    {
         return (TransferBoostError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, TransferBoostError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_PurchaseBoostError_Formatter : IonFormatter<PurchaseBoostError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public PurchaseBoostError Read(CborReader reader)
    {
         return (PurchaseBoostError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, PurchaseBoostError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SendGiftError_Formatter : IonFormatter<SendGiftError>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SendGiftError Read(CborReader reader)
    {
         return (SendGiftError)(IonFormatterStorage<u4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SendGiftError value)
    {
        var casted = (u4)value;
        IonFormatterStorage<u4>.Write(writer, casted);
    }
}

