//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record RtcEndpoint(string endpoint, IonArray<IceEndpoint> ices);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record IceEndpoint(string endpoint, string username, string password);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ServiceUssdResult(bool success, string message);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum CallFailedError : u4
{
    NONE = 0,
    CALLEE_OFFLINE = 1,
    INSUFFICIENT_BALANCE = 2,
    VERIFICATION_FAILED = 3,
    POOL_EMPTY_TRY_LATE = 4,
}

/// <summary>Open-enum helpers for <see cref="CallFailedError"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_CallFailedError_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this CallFailedError value)
        => value == CallFailedError.NONE || value == CallFailedError.CALLEE_OFFLINE || value == CallFailedError.INSUFFICIENT_BALANCE || value == CallFailedError.VERIFICATION_FAILED || value == CallFailedError.POOL_EMPTY_TRY_LATE;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this CallFailedError value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum DialCheckFailReason : u4
{
    COUNTRY_NOT_SUPPORT = 0,
    INVALID_NUMBER_COUNTRY = 1,
    INSUFFICIENT_BALANCE = 2,
    NUMBER_NOT_AVAILABLE = 3,
    INSUFFICIENT_POOL = 4,
    UNKNOWN_ERROR = 5,
}

/// <summary>Open-enum helpers for <see cref="DialCheckFailReason"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_DialCheckFailReason_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this DialCheckFailReason value)
        => value == DialCheckFailReason.COUNTRY_NOT_SUPPORT || value == DialCheckFailReason.INVALID_NUMBER_COUNTRY || value == DialCheckFailReason.INSUFFICIENT_BALANCE || value == DialCheckFailReason.NUMBER_NOT_AVAILABLE || value == DialCheckFailReason.INSUFFICIENT_POOL || value == DialCheckFailReason.UNKNOWN_ERROR;

    /// <summary>
    /// The raw <c>u4</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u4? UnknownValue(this DialCheckFailReason value)
        => value.IsKnown() ? null : (u4)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IVoiceInteraction : IIonService
{
    Task<bool> DisconnectFromVoiceChannel(guid spaceId, guid channelId, CancellationToken ct = default);
    Task KickMemberFromChannel(guid spaceId, guid channelId, guid memberId, CancellationToken ct = default);
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ICallInteraction : IIonService
{
    Task<IBeginCallResult> DingDongCreep(guid creepId, CancellationToken ct = default);
    Task<IPickUpCallResult> PickUpCall(guid callId, CancellationToken ct = default);
    Task RejectCall(guid callId, CancellationToken ct = default);
    Task HangupCall(guid callId, CancellationToken ct = default);
    Task<ServiceUssdResult> UssdExecute(string ussd, guid corlId, CancellationToken ct = default);
    Task<IDialCheckResult> BeginDialCheck(guid phoneId, CancellationToken ct = default);
    Task<IBeginCallResult> DialUp(guid phoneId, guid corlId, CancellationToken ct = default);
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IBeginCallResult : IIonUnion<IBeginCallResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessDingDong => this is SuccessDingDong;

    internal bool IsFailedDingDong => this is FailedDingDong;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessDingDong(string token, guid callId, RtcEndpoint rtc) : IBeginCallResult
{
    public string UnionKey => nameof(SuccessDingDong);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedDingDong(CallFailedError error) : IBeginCallResult
{
    public string UnionKey => nameof(FailedDingDong);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IBeginCallResult_Formatter : IonFormatter<IBeginCallResult>
{
    public IBeginCallResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IBeginCallResult", 2u);
        IBeginCallResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessDingDong>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedDingDong>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IBeginCallResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IBeginCallResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessDingDong n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessDingDong>.Write(writer, n_0);
        }

        else if (value is FailedDingDong n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedDingDong>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IBeginCallResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessDingDong_Formatter : IonFormatter<SuccessDingDong>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessDingDong Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "SuccessDingDong");
        var __token = IonFormatterStorage<string>.Read(reader);
        var __callid = IonFormatterStorage<guid>.Read(reader);
        var __rtc = IonFormatterStorage<RtcEndpoint>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__token, __callid, __rtc);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessDingDong value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<string>.Write(writer, value.token);
        IonFormatterStorage<guid>.Write(writer, value.callId);
        IonFormatterStorage<RtcEndpoint>.Write(writer, value.rtc);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedDingDong_Formatter : IonFormatter<FailedDingDong>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedDingDong Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedDingDong");
        var __error = IonFormatterStorage<CallFailedError>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedDingDong value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<CallFailedError>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IPickUpCallResult : IIonUnion<IPickUpCallResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessPickUp => this is SuccessPickUp;

    internal bool IsFailedPickUp => this is FailedPickUp;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessPickUp(string token, guid callId, RtcEndpoint rtc) : IPickUpCallResult
{
    public string UnionKey => nameof(SuccessPickUp);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedPickUp(string error) : IPickUpCallResult
{
    public string UnionKey => nameof(FailedPickUp);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IPickUpCallResult_Formatter : IonFormatter<IPickUpCallResult>
{
    public IPickUpCallResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IPickUpCallResult", 2u);
        IPickUpCallResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessPickUp>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedPickUp>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IPickUpCallResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IPickUpCallResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessPickUp n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessPickUp>.Write(writer, n_0);
        }

        else if (value is FailedPickUp n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedPickUp>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IPickUpCallResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessPickUp_Formatter : IonFormatter<SuccessPickUp>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessPickUp Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "SuccessPickUp");
        var __token = IonFormatterStorage<string>.Read(reader);
        var __callid = IonFormatterStorage<guid>.Read(reader);
        var __rtc = IonFormatterStorage<RtcEndpoint>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__token, __callid, __rtc);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessPickUp value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<string>.Write(writer, value.token);
        IonFormatterStorage<guid>.Write(writer, value.callId);
        IonFormatterStorage<RtcEndpoint>.Write(writer, value.rtc);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedPickUp_Formatter : IonFormatter<FailedPickUp>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedPickUp Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "FailedPickUp");
        var __error = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__error);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedPickUp value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<string>.Write(writer, value.error);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IDialCheckResult : IIonUnion<IDialCheckResult>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsSuccessDialCheck => this is SuccessDialCheck;

    internal bool IsFailedDialCheck => this is FailedDialCheck;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SuccessDialCheck(i4 priceMin, guid corelId, guid corlId) : IDialCheckResult
{
    public string UnionKey => nameof(SuccessDialCheck);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record FailedDialCheck(DialCheckFailReason reason, i4 priceMin) : IDialCheckResult
{
    public string UnionKey => nameof(FailedDialCheck);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IDialCheckResult_Formatter : IonFormatter<IDialCheckResult>
{
    public IDialCheckResult Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IDialCheckResult", 2u);
        IDialCheckResult result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<SuccessDialCheck>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<FailedDialCheck>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IDialCheckResult", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IDialCheckResult value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is SuccessDialCheck n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<SuccessDialCheck>.Write(writer, n_0);
        }

        else if (value is FailedDialCheck n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<FailedDialCheck>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IDialCheckResult' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SuccessDialCheck_Formatter : IonFormatter<SuccessDialCheck>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SuccessDialCheck Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "SuccessDialCheck");
        var __pricemin = IonFormatterStorage<i4>.Read(reader);
        var __corelid = IonFormatterStorage<guid>.Read(reader);
        var __corlid = IonFormatterStorage<guid>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__pricemin, __corelid, __corlid);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SuccessDialCheck value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.priceMin);
        IonFormatterStorage<guid>.Write(writer, value.corelId);
        IonFormatterStorage<guid>.Write(writer, value.corlId);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FailedDialCheck_Formatter : IonFormatter<FailedDialCheck>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FailedDialCheck Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "FailedDialCheck");
        var __reason = IonFormatterStorage<DialCheckFailReason>.Read(reader);
        var __pricemin = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__reason, __pricemin);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FailedDialCheck value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<DialCheckFailReason>.Write(writer, value.reason);
        IonFormatterStorage<i4>.Write(writer, value.priceMin);
        writer.WriteEndArray();
    }
}


