import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "node:path";
import tailwind from "tailwindcss";
import autoprefixer from "autoprefixer";
import vueDevTools from "vite-plugin-vue-devtools";
import SvgImporter from "vite-svg-loader";
import fs from "fs";
import zlib from "node:zlib";
export default defineConfig({
  server: {
    port: 5005,
    // The widget is framed by sites that are not ours and its session cookie is SameSite=None,
    // which browsers only accept over TLS — so development is https or it is nothing useful.
    // The pair is generated by scripts/cert.gen.ps1 (or .sh) and is not in the repository; without
    // it the dev server still starts, over plain http, rather than refusing to boot.
    https: fs.existsSync("localhost-key.pem") && fs.existsSync("localhost.pem")
      ? { key: "localhost-key.pem", cert: "localhost.pem" }
      : undefined,
  },
  css: {
    postcss: {
      plugins: [tailwind(), autoprefixer()],
    },
  },
  plugins: [
    vue(),
    vueDevTools(),
    SvgImporter(),
    {
      // Compress once here rather than per request in Kestrel: the files are immutable and named
      // by content hash, so the work has exactly one right moment to happen, and the identity
      // server then spends no CPU on it at all. AegisFeature serves whichever sibling the
      // request's Accept-Encoding allows.
      name: "precompress",
      closeBundle() {
        const dir = path.resolve("dist");
        if (!fs.existsSync(dir)) return;

        const compressible = /\.(js|css|html|svg|json|map|txt)$/i;
        let saved = 0;

        const walk = (d: string) => {
          for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
            const full = path.join(d, entry.name);
            if (entry.isDirectory()) { walk(full); continue; }
            if (!compressible.test(entry.name)) continue;

            const raw = fs.readFileSync(full);
            // Below a kilobyte the framing costs more than the compression saves.
            if (raw.length < 1024) continue;

            const br = zlib.brotliCompressSync(raw, {
              params: {
                [zlib.constants.BROTLI_PARAM_QUALITY]: zlib.constants.BROTLI_MAX_QUALITY,
                [zlib.constants.BROTLI_PARAM_SIZE_HINT]: raw.length,
              },
            });
            const gz = zlib.gzipSync(raw, { level: zlib.constants.Z_BEST_COMPRESSION });

            fs.writeFileSync(full + ".br", br);
            fs.writeFileSync(full + ".gz", gz);
            saved += raw.length - br.length;
          }
        };

        walk(dir);
        console.log(`✅ Precompressed dist, ${(saved / 1024).toFixed(1)} kB saved over brotli`);
      },
    },
    {
      name: "version-generator",
      closeBundle() {
        const dir = path.resolve("dist");
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }

        const version = Date.now().toString();
        const filePath = path.join(dir, "tag.json");
        fs.writeFileSync(filePath, JSON.stringify({ version }), "utf8");
        console.log(`✅ Version tag written to ${filePath}`);
      },
    },
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  define: {
    __VUE_PROD_DEVTOOLS__: false,
    // Nothing here is written with the Options API — not the widget, not @argon/ui, not reka-ui.
    __VUE_OPTIONS_API__: false,
  },
  worker: {
    format: "es",
  },
});
