---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argon-api
  labels:
    app: argon-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: argon-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: argon-api
    spec:
      containers:
        - name: argon-api
          image: argon-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          envFrom:
            - configMapRef:
                name: argon-api-env
            - secretRef:
                name: argon-api-secrets
      terminationGracePeriodSeconds: 180