---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmq
  labels:
    app: rmq
spec:
  serviceName: "rmq"
  replicas: 1
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
        - name: rmq
          image: docker.io/library/rabbitmq:3.13-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - configMapRef:
                name: rmq-env
          volumeMounts:
            - name: apphost-rmq-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: apphost-rmq-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
