---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtpdev
  labels:
    app: smtpdev
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: smtpdev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smtpdev
    spec:
      containers:
        - name: smtpdev
          image: rnwood/smtp4dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: tcp
              containerPort: 25
          envFrom:
            - configMapRef:
                name: smtpdev-env
      terminationGracePeriodSeconds: 180