---
apiVersion: v1
kind: Service
metadata:
  name: smtpdev
spec:
  type: ClusterIP
  selector:
    app: smtpdev
  ports:
    - name: http
      port: 3080
      targetPort: 80
    - name: tcp
      port: 2525
      targetPort: 25
