import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import type { Plugin, ServerOptions } from "vite";

/**
 * The build-time half of how the server serves these apps.
 *
 * Nothing in front of Argon compresses anything — Kestrel has no response compression configured
 * and the proxy adds none — so each app writes a brotli and a gzip sibling next to every asset
 * worth compressing, and `UsePrecompressedStaticFiles` on the .NET side picks between them per
 * request. Doing it here rather than there is what makes brotli's maximum quality affordable: the
 * files are named by content hash and never change, so the work has exactly one right moment.
 */
export function precompress(): Plugin {
  // Not images or fonts: those formats are already compressed, and a .br sibling of a .woff2 is
  // larger than the file it shadows.
  const compressible = /\.(js|css|html|svg|json|map|txt|webmanifest)$/i;

  // Below a kilobyte the framing costs more than the compression saves.
  const floor = 1024;

  return {
    name: "argon:precompress",
    closeBundle() {
      const dir = path.resolve("dist");
      if (!fs.existsSync(dir)) return;

      let saved = 0;

      const walk = (directory: string) => {
        for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
          const full = path.join(directory, entry.name);

          if (entry.isDirectory()) {
            walk(full);
            continue;
          }

          if (!compressible.test(entry.name)) continue;

          const raw = fs.readFileSync(full);
          if (raw.length < floor) continue;

          const brotli = zlib.brotliCompressSync(raw, {
            params: {
              [zlib.constants.BROTLI_PARAM_QUALITY]: zlib.constants.BROTLI_MAX_QUALITY,
              [zlib.constants.BROTLI_PARAM_SIZE_HINT]: raw.length,
            },
          });
          const gzip = zlib.gzipSync(raw, { level: zlib.constants.Z_BEST_COMPRESSION });

          fs.writeFileSync(`${full}.br`, brotli);
          fs.writeFileSync(`${full}.gz`, gzip);
          saved += raw.length - brotli.length;
        }
      };

      walk(dir);
      console.log(`✅ Precompressed dist, ${(saved / 1024).toFixed(1)} kB saved over brotli`);
    },
  };
}

/**
 * A `tag.json` in the build output, which is how a running page finds out it is stale.
 */
export function versionTag(): Plugin {
  return {
    name: "argon:version-tag",
    closeBundle() {
      const dir = path.resolve("dist");
      fs.mkdirSync(dir, { recursive: true });

      const file = path.join(dir, "tag.json");
      fs.writeFileSync(file, JSON.stringify({ version: Date.now().toString() }), "utf8");
      console.log(`✅ Version tag written to ${file}`);
    },
  };
}

/**
 * The dev server's TLS, if there is a certificate to use.
 *
 * Both apps are reached over https in development — one is framed by sites that are not ours and
 * keeps a `SameSite=None` cookie, the other authenticates through an OAuth redirect — and browsers
 * only honour either over TLS. The pair is generated by `scripts/cert.gen.ps1` (or `.sh`) and is
 * deliberately not in the repository, so its absence has to mean a plain-http dev server rather
 * than a dev server that refuses to start.
 */
export function devServerHttps(dir = process.cwd()): ServerOptions["https"] {
  const key = path.join(dir, "localhost-key.pem");
  const cert = path.join(dir, "localhost.pem");

  if (!fs.existsSync(key) || !fs.existsSync(cert)) return undefined;

  return { key, cert };
}
