//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

public sealed class Ion_PrivacyInteraction_ServiceExecutor(AsyncServiceScope scope) : IServiceExecutorRouter
{
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetPrivacyRule_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IPrivacyInteraction>();
    
        const int argumentSize = 2;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __key = IonFormatterStorage<string>.Read(reader);
        var __spaceid = reader.ReadNullable<guid>();
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetPrivacyRule(__key, __spaceid);
        
        IonFormatterStorage<PrivacyRuleView>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task SetPrivacyRule_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IPrivacyInteraction>();
    
        const int argumentSize = 5;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __key = IonFormatterStorage<string>.Read(reader);
        var __mode = IonFormatterStorage<PrivacyRuleMode>.Read(reader);
        var __spaceid = reader.ReadNullable<guid>();
        var __allow = IonFormatterStorage<guid>.ReadArray(reader);
        var __deny = IonFormatterStorage<guid>.ReadArray(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.SetPrivacyRule(__key, __mode, __spaceid, __allow, __deny);
        
        IonFormatterStorage<bool>.Write(writer, result);
    }

    
    
    
        public Task RouteExecuteAsync(string methodName, CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        
        if (methodName.Equals("GetPrivacyRule", StringComparison.InvariantCultureIgnoreCase))
            return GetPrivacyRule_Execute(reader, writer, ct);
        if (methodName.Equals("SetPrivacyRule", StringComparison.InvariantCultureIgnoreCase))
            return SetPrivacyRule_Execute(reader, writer, ct);

        
        throw new InvalidOperationException("no method defined");
    }
    
    private static readonly string[] __allowedStreamingMethods = [
        
    ];
    
    public bool IsAllowInputStream(string methodName) => __allowedStreamingMethods.Contains(methodName);
}

