//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ArgonContracts;

public sealed class Ion_UserInteraction_ServiceExecutor(AsyncServiceScope scope) : IServiceExecutorRouter
{
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetMe_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetMe();
        
        IonFormatterStorage<ArgonUser>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task CreateSpace_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __request = IonFormatterStorage<CreateServerRequest>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.CreateSpace(__request);
        
        IonFormatterStorage<ICreateSpaceResult>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetSpaces_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetSpaces();
        
        IonFormatterStorage<ArgonSpaceBase>.WriteArray(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task UpdateMe_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __request = IonFormatterStorage<UserEditInput>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.UpdateMe(__request);
        
        IonFormatterStorage<ArgonUser>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task JoinToSpace_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __invitecode = IonFormatterStorage<InviteCode>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.JoinToSpace(__invitecode);
        
        IonFormatterStorage<IJoinToSpaceResult>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task BroadcastPresence_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __presence = IonFormatterStorage<UserActivityPresence>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.BroadcastPresence(__presence);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task RemoveBroadcastPresence_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.RemoveBroadcastPresence();
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetMyFeatures_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetMyFeatures();
        
        IonFormatterStorage<FeatureFlag>.WriteArray(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetMyProfile_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetMyProfile();
        
        IonFormatterStorage<ArgonUserProfile>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task BeginUploadAvatar_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.BeginUploadAvatar();
        
        IonFormatterStorage<IUploadFileResult>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task CompleteUploadAvatar_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __blobid = IonFormatterStorage<guid>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.CompleteUploadAvatar(__blobid);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task BeginUploadProfileHeader_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.BeginUploadProfileHeader();
        
        IonFormatterStorage<IUploadFileResult>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task CompleteUploadProfileHeader_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __blobid = IonFormatterStorage<guid>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.CompleteUploadProfileHeader(__blobid);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetTodayStats_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetTodayStats();
        
        IonFormatterStorage<TodayStats>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetMyLevel_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetMyLevel();
        
        IonFormatterStorage<MyLevelDetails>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task ClaimLevelCoin_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.ClaimLevelCoin();
        
        IonFormatterStorage<bool>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetGlobalBadges_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 0;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetGlobalBadges();
        
        IonFormatterStorage<GlobalBadges>.Write(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task AckChannel_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 2;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __channelid = IonFormatterStorage<guid>.Read(reader);
        var __lastreadmessageid = IonFormatterStorage<i8>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.AckChannel(__channelid, __lastreadmessageid);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task MuteTarget_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 5;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __targetid = IonFormatterStorage<guid>.Read(reader);
        var __targettype = IonFormatterStorage<MuteTargetKind>.Read(reader);
        var __mutelevel = IonFormatterStorage<MuteLevelType>.Read(reader);
        var __suppresseveryone = IonFormatterStorage<bool>.Read(reader);
        var __expiresat = reader.ReadNullable<datetime>();
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.MuteTarget(__targetid, __targettype, __mutelevel, __suppresseveryone, __expiresat);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task UnmuteTarget_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __targetid = IonFormatterStorage<guid>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.UnmuteTarget(__targetid);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task GetNotificationFeed_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 2;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __limit = IonFormatterStorage<i4>.Read(reader);
        var __before = reader.ReadNullable<datetime>();
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.GetNotificationFeed(__limit, __before);
        
        IonFormatterStorage<SystemNotificationDto>.WriteArray(writer, result);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task MarkNotificationRead_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __notificationid = IonFormatterStorage<guid>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.MarkNotificationRead(__notificationid);
    }
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task MarkAllNotificationsRead_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<IUserInteraction>();
    
        const int argumentSize = 1;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __type = reader.ReadNullable<string>();
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        await service.MarkAllNotificationsRead(__type);
    }

    
    
    
        public Task RouteExecuteAsync(string methodName, CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        
        if (methodName.Equals("GetMe", StringComparison.InvariantCultureIgnoreCase))
            return GetMe_Execute(reader, writer, ct);
        if (methodName.Equals("CreateSpace", StringComparison.InvariantCultureIgnoreCase))
            return CreateSpace_Execute(reader, writer, ct);
        if (methodName.Equals("GetSpaces", StringComparison.InvariantCultureIgnoreCase))
            return GetSpaces_Execute(reader, writer, ct);
        if (methodName.Equals("UpdateMe", StringComparison.InvariantCultureIgnoreCase))
            return UpdateMe_Execute(reader, writer, ct);
        if (methodName.Equals("JoinToSpace", StringComparison.InvariantCultureIgnoreCase))
            return JoinToSpace_Execute(reader, writer, ct);
        if (methodName.Equals("BroadcastPresence", StringComparison.InvariantCultureIgnoreCase))
            return BroadcastPresence_Execute(reader, writer, ct);
        if (methodName.Equals("RemoveBroadcastPresence", StringComparison.InvariantCultureIgnoreCase))
            return RemoveBroadcastPresence_Execute(reader, writer, ct);
        if (methodName.Equals("GetMyFeatures", StringComparison.InvariantCultureIgnoreCase))
            return GetMyFeatures_Execute(reader, writer, ct);
        if (methodName.Equals("GetMyProfile", StringComparison.InvariantCultureIgnoreCase))
            return GetMyProfile_Execute(reader, writer, ct);
        if (methodName.Equals("BeginUploadAvatar", StringComparison.InvariantCultureIgnoreCase))
            return BeginUploadAvatar_Execute(reader, writer, ct);
        if (methodName.Equals("CompleteUploadAvatar", StringComparison.InvariantCultureIgnoreCase))
            return CompleteUploadAvatar_Execute(reader, writer, ct);
        if (methodName.Equals("BeginUploadProfileHeader", StringComparison.InvariantCultureIgnoreCase))
            return BeginUploadProfileHeader_Execute(reader, writer, ct);
        if (methodName.Equals("CompleteUploadProfileHeader", StringComparison.InvariantCultureIgnoreCase))
            return CompleteUploadProfileHeader_Execute(reader, writer, ct);
        if (methodName.Equals("GetTodayStats", StringComparison.InvariantCultureIgnoreCase))
            return GetTodayStats_Execute(reader, writer, ct);
        if (methodName.Equals("GetMyLevel", StringComparison.InvariantCultureIgnoreCase))
            return GetMyLevel_Execute(reader, writer, ct);
        if (methodName.Equals("ClaimLevelCoin", StringComparison.InvariantCultureIgnoreCase))
            return ClaimLevelCoin_Execute(reader, writer, ct);
        if (methodName.Equals("GetGlobalBadges", StringComparison.InvariantCultureIgnoreCase))
            return GetGlobalBadges_Execute(reader, writer, ct);
        if (methodName.Equals("AckChannel", StringComparison.InvariantCultureIgnoreCase))
            return AckChannel_Execute(reader, writer, ct);
        if (methodName.Equals("MuteTarget", StringComparison.InvariantCultureIgnoreCase))
            return MuteTarget_Execute(reader, writer, ct);
        if (methodName.Equals("UnmuteTarget", StringComparison.InvariantCultureIgnoreCase))
            return UnmuteTarget_Execute(reader, writer, ct);
        if (methodName.Equals("GetNotificationFeed", StringComparison.InvariantCultureIgnoreCase))
            return GetNotificationFeed_Execute(reader, writer, ct);
        if (methodName.Equals("MarkNotificationRead", StringComparison.InvariantCultureIgnoreCase))
            return MarkNotificationRead_Execute(reader, writer, ct);
        if (methodName.Equals("MarkAllNotificationsRead", StringComparison.InvariantCultureIgnoreCase))
            return MarkAllNotificationsRead_Execute(reader, writer, ct);

        
        throw new InvalidOperationException("no method defined");
    }
    
    private static readonly string[] __allowedStreamingMethods = [
        
    ];
    
    public bool IsAllowInputStream(string methodName) => __allowedStreamingMethods.Contains(methodName);
}

