// <auto-generated />
using System;
using Argon.Api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Argon.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241020175631_AddedOrleansRemindersTable")]
    partial class AddedOrleansRemindersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Argon.Api.Orleansmembershiptable", b =>
                {
                    b.Property<string>("Deploymentid")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("deploymentid");

                    b.Property<string>("Address")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("address");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("hostname");

                    b.Property<DateTime>("Iamalivetime")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("iamalivetime");

                    b.Property<int?>("Proxyport")
                        .HasColumnType("integer")
                        .HasColumnName("proxyport");

                    b.Property<string>("Siloname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("siloname");

                    b.Property<DateTime>("Starttime")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("starttime");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Suspecttimes")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("suspecttimes");

                    b.HasKey("Deploymentid", "Address", "Port", "Generation")
                        .HasName("pk_membershiptable_deploymentid");

                    b.ToTable("orleansmembershiptable", (string)null);
                });

            modelBuilder.Entity("Argon.Api.Orleansmembershipversiontable", b =>
                {
                    b.Property<string>("Deploymentid")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("deploymentid");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("version");

                    b.HasKey("Deploymentid")
                        .HasName("pk_orleansmembershipversiontable_deploymentid");

                    b.ToTable("orleansmembershipversiontable", (string)null);
                });

            modelBuilder.Entity("Argon.Api.Orleansquery", b =>
                {
                    b.Property<string>("Querykey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("querykey");

                    b.Property<string>("Querytext")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("querytext");

                    b.HasKey("Querykey")
                        .HasName("orleansquery_key");

                    b.ToTable("orleansquery", (string)null);
                });

            modelBuilder.Entity("Argon.Api.Orleansreminderstable", b =>
                {
                    b.Property<string>("Serviceid")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("serviceid");

                    b.Property<string>("Grainid")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("grainid");

                    b.Property<string>("Remindername")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("remindername");

                    b.Property<int>("Grainhash")
                        .HasColumnType("integer")
                        .HasColumnName("grainhash");

                    b.Property<long>("Period")
                        .HasColumnType("bigint")
                        .HasColumnName("period");

                    b.Property<DateTime>("Starttime")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("starttime");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Serviceid", "Grainid", "Remindername")
                        .HasName("pk_reminderstable_serviceid_grainid_remindername");

                    b.ToTable("orleansreminderstable", (string)null);
                });

            modelBuilder.Entity("Argon.Api.Orleansstorage", b =>
                {
                    b.Property<string>("Grainidextensionstring")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("grainidextensionstring");

                    b.Property<int>("Grainidhash")
                        .HasColumnType("integer")
                        .HasColumnName("grainidhash");

                    b.Property<long>("Grainidn0")
                        .HasColumnType("bigint")
                        .HasColumnName("grainidn0");

                    b.Property<long>("Grainidn1")
                        .HasColumnType("bigint")
                        .HasColumnName("grainidn1");

                    b.Property<int>("Graintypehash")
                        .HasColumnType("integer")
                        .HasColumnName("graintypehash");

                    b.Property<string>("Graintypestring")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("graintypestring");

                    b.Property<DateTime>("Modifiedon")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifiedon");

                    b.Property<byte[]>("Payloadbinary")
                        .HasColumnType("bytea")
                        .HasColumnName("payloadbinary");

                    b.Property<string>("Serviceid")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("serviceid");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasIndex(new[] { "Grainidhash", "Graintypehash" }, "ix_orleansstorage");

                    b.ToTable("orleansstorage", (string)null);
                });

            modelBuilder.Entity("Argon.Api.Orleansmembershiptable", b =>
                {
                    b.HasOne("Argon.Api.Orleansmembershipversiontable", "Deployment")
                        .WithMany("Orleansmembershiptables")
                        .HasForeignKey("Deploymentid")
                        .IsRequired()
                        .HasConstraintName("fk_membershiptable_membershipversiontable_deploymentid");

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Argon.Api.Orleansmembershipversiontable", b =>
                {
                    b.Navigation("Orleansmembershiptables");
                });
#pragma warning restore 612, 618
        }
    }
}
